import React,{useEffect,useState} from 'react';
import api from '../../lib/api';
export default function PayEarningRules({rules,onChange,disabled}){
 const [catalog,setCatalog]=useState([]),[query,setQuery]=useState('');
 useEffect(()=>{api.get('/payroll/employee-records/configuration/catalog/pay-categories').then(({data})=>setCatalog(data.tables?.Export||[])).catch(()=>{});},[]);
 const patch=(i,k,v)=>onChange(rules.map((r,j)=>i===j?{...r,[k]:v}:r));
 const add=name=>onChange([...rules,{code:`earning_${Date.now()}`,name:name||'New earning',basis:'fixed_rate',rate:0,multiplier:1,taxable:null,superable:null}]);
 return <section id="earning-rules" className="border rounded-xl p-4 my-4"><h3>Earning category rates and rules</h3><p className="text-sm my-2">Amount = units × rate × multiplier. Choose a fixed dollar rate or the employee’s base hourly rate. Enter additional earnings only; leave and accrual hours stay in the existing hours fields.</p><fieldset disabled={disabled}><div className="flex gap-3 my-3"><label>Find category<input className="border rounded p-2 block" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Add imported category<select aria-label="Add imported earning category" className="border rounded p-2 block" value="" onChange={e=>e.target.value&&add(e.target.value)}><option value="">Choose category…</option>{catalog.filter(c=>!rules.some(r=>r.name===c.PayCategoryName)&&String(c.PayCategoryName).toLowerCase().includes(query.toLowerCase())).map((c,i)=><option key={i}>{c.PayCategoryName}</option>)}</select></label><button type="button" className="pay-outline" onClick={()=>add('')}>Create category</button></div>{rules.map((r,i)=><div key={r.code} className="border-t py-3 grid sm:grid-cols-3 gap-3"><label>Name<input className="border rounded p-2 w-full" value={r.name} onChange={e=>patch(i,'name',e.target.value)}/></label><label>Calculation<select className="border rounded p-2 w-full" value={r.basis} onChange={e=>patch(i,'basis',e.target.value)}><option value="fixed_rate">Units × fixed rate × multiplier</option><option value="base_rate">Hours × employee base rate × multiplier</option></select></label><label>{r.basis==='fixed_rate'?'Rate $':'Employee base rate'}<input type="number" min="0" step="any" disabled={r.basis==='base_rate'} className="border rounded p-2 w-full" value={r.basis==='base_rate'?'':r.rate} onChange={e=>patch(i,'rate',Number(e.target.value))}/></label><label>Multiplier<input type="number" min="0" max="100" step="any" className="border rounded p-2 w-full" value={r.multiplier} onChange={e=>patch(i,'multiplier',Number(e.target.value))}/></label>{[['taxable','PAYG'],['superable','Super']].map(([k,l])=><label key={k}>{l}<select className="border rounded p-2 w-full" value={r[k]==null?'':String(r[k])} onChange={e=>patch(i,k,e.target.value===''?null:e.target.value==='true')}><option value="">Select treatment</option><option value="true">Include</option><option value="false">Exclude</option></select></label>)}<button type="button" className="underline text-sm" onClick={()=>onChange(rules.filter((_,j)=>j!==i))}>Remove rule</button></div>)}</fieldset><p className="text-xs mt-2">Save calculation defaults below. Existing runs retain the rules already selected in that run.</p></section>;
}
