import React,{useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
import {PayCard} from './PayShell';
import DateField from './DateField';
export default function PayOverview(){
 const [week,setWeek]=useState(''),[runs,setRuns]=useState([]),[error,setError]=useState(''),[weekStart,setWeekStart]=useState('friday');const navigate=useNavigate();
 useEffect(()=>{api.get('/payroll/settings').then(({data})=>setWeekStart(data.week_starts||'friday')).catch(e=>setError(apiError(e)||'Could not load payroll calendar'));api.get('/payroll/workbench/runs/list').then(({data})=>setRuns(data.runs)).catch(e=>setError(apiError(e)||'Could not load pay runs.'));},[]);
 function start(){if(new Date(`${week}T12:00:00`).getDay()!==['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].indexOf(weekStart)){setError(`Choose ${weekStart} at the start of the pay week.`);return;}navigate(`/app/pay/payroll?week=${week}`);}
 return <div className="space-y-5"><PayCard title="Start a new pay run"><p className="text-slate-600 mb-4">Choose the working week. Current Simpro employees and their submitted phone hours will be loaded for you to check and edit.</p><div className="flex flex-wrap gap-4 items-end"><label className="text-sm font-semibold">Week starting {weekStart[0].toUpperCase()+weekStart.slice(1)}<br/><DateField className="border rounded-lg p-3 mt-2" value={week} onChange={e=>setWeek(e.target.value)}/></label><button disabled={!week} onClick={start} className="rounded-lg bg-amber-500 px-5 py-3 font-bold disabled:opacity-40">Start / open pay run</button></div><p className="text-sm text-slate-500 mt-4">1. Select week · 2. Review employees · 3. Lock figures and export wages · 4. Confirm payment and email payslips.</p>{error&&<p role="alert" className="text-red-700 mt-3">{typeof error==='string'?error:JSON.stringify(error)}</p>}</PayCard><PayCard title="Saved pay runs"><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-3">Working week</th><th>Payment date</th><th>Employees</th><th>Status</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.week} className="border-b"><td className="p-3">{r.week}</td><td>{r.payday}</td><td>{r.employees}</td><td>{r.issued?'Payslips issued - check email status':r.state==='finalized'?'Locked for payment':'Draft / in review'}</td><td><Link className="text-indigo-700 underline" to={`/app/pay/payroll?week=${r.week}`}>Open run</Link></td></tr>)}</tbody></table>{!runs.length&&<p className="p-5 text-slate-500">Start your first run above. Employees come from Simpro; edit payroll rates and bank details within a pay run.</p>}</div></PayCard></div>;
}

export async function downloadCsv(periodId,fmt){const {data}=await api.get('/payroll/export',{params:{period_id:periodId,fmt},responseType:'blob'});const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=`timesheets-${periodId}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
