import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
export default function PayrollSuperFundSettings(){
 const can=useCan(),edit=can('payroll','edit'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[checks,setChecks]=useState({}),[dirty,setDirty]=useState(false);
 useEffect(()=>{api.get('/payroll/employee-records/configuration/super-funds').then(r=>setData(r.data)).catch(e=>setMessage(apiError(e)));},[]);
 function patch(index,key,value){setData(d=>({...d,items:d.items.map((f,i)=>i===index?{...f,[key]:value}:f)}));setChecks({});setDirty(true);}
 async function check(index){setBusy(true);try{const {data:r}=await api.post('/payroll/employee-records/configuration/super-funds/check',data.items[index]);setChecks(c=>({...c,[index]:r}));}catch(e){setChecks(c=>({...c,[index]:{error:apiError(e)||'Fund check unavailable'}}));}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{setData((await api.put('/payroll/employee-records/configuration/super-funds',data)).data);setDirty(false);setMessage('Shared super fund list saved. Select the fund in each employee record.');}catch(e){setMessage(apiError(e));}finally{setBusy(false);}}
 return <section className="pay-panel" id="super-funds"><h3 className="font-bold text-lg">Super funds</h3><p className="text-sm my-3">Maintain fund names and USIs once for the company. Employees select from this list and retain their own member numbers. Changes here do not rewrite employee selections or past pay runs.</p>{message&&<p role="status">{String(message)}</p>}{data&&<><div className="space-y-3">{data.items.map((f,i)=><div className="border rounded-xl p-3" key={i}><div className="grid sm:grid-cols-3 gap-3"><label>Fund name<input aria-label={`Fund name ${i+1}`} disabled={!edit||busy} className="border rounded p-2 w-full" value={f.name} maxLength={160} onChange={e=>patch(i,'name',e.target.value)}/></label><label>Fund USI<input aria-label={`Fund USI ${i+1}`} disabled={!edit||busy} className="border rounded p-2 w-full" value={f.usi} maxLength={32} onChange={e=>patch(i,'usi',e.target.value)}/></label><label className="self-center"><input disabled={!edit||busy} type="checkbox" checked={f.active} onChange={e=>patch(i,'active',e.target.checked)}/> Available for selection</label></div><button type="button" className="pay-outline mt-3" disabled={busy||!f.name.trim()||!f.usi.trim()} onClick={()=>check(i)}>Check USI against recorded fund</button>{checks[i]&&<div role="status" className="text-sm mt-2"><strong>{checks[i].error||({matched:'Fund name matches this USI',name_mismatch:'Recorded fund name does not match this USI',not_found:'USI not found in the official register',inactive:'USI is outside its recorded effective dates'}[checks[i].status])}</strong>{checks[i].matches?.map((m,j)=><p key={j}>{m.fund_name} / {m.product_name} / {m.usi}{m.restricted?' / Contact the fund about contribution restrictions':''}</p>)}<p>{checks[i].note}</p></div>}</div>)}</div>{!data.items.length&&<p>No shared funds recorded yet.</p>}<div className="flex gap-3 mt-3"><button type="button" className="pay-outline" disabled={!edit||busy} onClick={()=>{setData(d=>({...d,items:[...d.items,{name:'',usi:'',active:true}]}));setDirty(true);}}>Add super fund</button><button type="button" className="pay-gold" disabled={!edit||busy||!dirty} onClick={save}>Save super funds</button></div></>}</section>;
}
