import DateField from './DateField';
import React,{useEffect,useState} from 'react';
import api from '../../lib/api';
export default function PayrollIssuing({week,revision,workers,dirty,locked,onCompleted=()=>{}}) {
 const [batch,setBatch]=useState(null);
 const [data,setData]=useState(null),[paidDate,setPaidDate]=useState(''),[reference,setReference]=useState(''),[verified,setVerified]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[issuedRevision,setIssuedRevision]=useState(''),[worker,setWorker]=useState('');
 useEffect(()=>{let active=true;api.get(`/payroll/workbench/${week}/payslips/status`).then(({data:d})=>{if(active)setData(d);api.get(`/payroll/workbench/${week}/delivery/${revision}`).then(r=>{if(active)setBatch(r.data);});}).catch(()=>{if(active)setMessage('Payslip status unavailable.');});return()=>{active=false;};},[week,revision]);
 async function sendBatch(){const response=await api.get(`/payroll/workbench/${week}/delivery/${revision}`);for(const person of response.data.recipients){if(person.status!=='pending')continue;setMessage(`Sending individual payslip: ${person.name}`);await api.post(`/payroll/workbench/${week}/delivery/${revision}/${encodeURIComponent(person.worker_id)}`);}const refreshed=await api.get(`/payroll/workbench/${week}/delivery/${revision}`);setBatch(refreshed.data);onCompleted();setMessage('Batch processed. Accepted means the email service accepted the message, not confirmed delivery. Check any remaining or uncertain items below.');}
 async function issue(){setBusy(true);try{await api.post(`/payroll/workbench/${week}/complete`,{revision,paid_date:paidDate,payment_reference:reference,particulars_verified:verified});const {data:d}=await api.get(`/payroll/workbench/${week}/payslips/status`);setData(d);await sendBatch();}catch(e){setMessage(typeof e.response?.data?.detail==='string'?e.response.data.detail:'Could not complete payslip batch');const r=await api.get(`/payroll/workbench/${week}/delivery/${revision}`).catch(()=>null);if(r)setBatch(r.data);}finally{setBusy(false);}}
 async function resume(){setBusy(true);try{await sendBatch();}catch(e){setMessage(e.response?.data?.detail||'Batch paused. Reload status before retrying.');}finally{setBusy(false);}}
 async function download(){try{const {data:blob}=await api.get(`/payroll/workbench/${week}/payslips/${issuedRevision}/${encodeURIComponent(worker)}/pdf`,{responseType:'blob'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`payslip-${week}-r${issuedRevision}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage('Could not download this employee’s issued payslip.');}}
 return <details open className="border rounded p-4 my-4"><summary className="font-semibold">Send private payslips</summary><p className="text-sm my-3">After locking reviewed figures and confirming bank payment, complete the run to send a separate private payslip to each employee. Keep this page open until the batch finishes. Pending messages can be resumed later.</p>
 {!data?.enabled&&<p className="bg-amber-50 p-3 my-2 text-sm">Issuing is disabled until deployment and parallel-run validation are complete. Draft previews remain available.</p>}
 <fieldset disabled={!data?.enabled||busy||dirty||!locked} className="space-y-2 mt-3"><label className="block text-sm">Actual wage payment date<DateField className="border rounded p-2 block" value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label><label className="block text-sm">Payment confirmation reference<input className="border rounded p-2 block" maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="block text-sm"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> I have confirmed wages were paid and checked every employee’s payslip particulars, deductions and allowances.</label><button type="button" disabled={!verified||!paidDate||!reference.trim()} className="border rounded p-2 disabled:opacity-40" onClick={issue}>Complete pay run and send payslips</button></fieldset>
 {!!data?.issues.length&&<div className="mt-3"><label className="text-sm">Issued version<select className="border rounded p-2 m-2" value={issuedRevision} onChange={e=>setIssuedRevision(e.target.value)}><option value="">Select…</option>{data.issues.map(i=><option key={i.revision} value={i.revision}>Revision {i.revision} · paid {i.paid_date} · issue recorded</option>)}</select></label><label className="text-sm">Payslip employee<select className="border rounded p-2 m-2" value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Select…</option>{workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button type="button" disabled={!worker||!issuedRevision} className="border rounded p-2" onClick={download}>Download printable payslip</button></div>}
 {batch?.prepared&&<div className="mt-3"><h4 className="font-semibold">Email batch status</h4><p className="text-sm">Needs check / sending or unknown: contact the pay officer and check Sent Items before any manual resend. These messages are never retried automatically.</p>{batch.recipients.map(p=><p key={p.worker_id} className="text-sm border-b py-1">{p.name} · {p.email} · {p.status}</p>)}<button disabled={busy||dirty||!locked||!batch.recipients.some(p=>p.status==='pending')} className="border rounded p-2 mt-2 disabled:opacity-40" onClick={resume}>Send remaining pending payslips</button></div>}
 {message&&<p role="status" className="text-sm my-2">{message}</p>}
 </details>;
}
