import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
export default function PayrollSuperFundSettings(){
 const can=useCan(),edit=can('payroll','edit'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[checks,setChecks]=useState({}),[dirty,setDirty]=useState(false);
 useEffect(()=>{api.get('/payroll/employee-records/configuration/super-funds').then(r=>{setData(r.data);setChecks(Object.fromEntries(r.data.items.map((f,i)=>[i,r.data.checks?.[f.usi]])));}).catch(e=>setMessage(apiError(e)));},[]);
 function patch(index,key,value){setData(d=>({...d,items:d.items.map((f,i)=>i===index?{...f,[key]:value}:f)}));if(key==='name'||key==='usi')setChecks(c=>({...c,[index]:null}));setDirty(true);}
 async function check(index){setBusy(true);try{const {data:r}=await api.post('/payroll/employee-records/configuration/super-funds/check',data.items[index]);setChecks(c=>({...c,[index]:r}));}catch(e){setChecks(c=>({...c,[index]:{error:apiError(e)||'Fund check unavailable'}}));}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{setData((await api.put('/payroll/employee-records/configuration/super-funds',{revision:data.revision,items:data.items})).data);setDirty(false);setMessage('Shared super fund list saved. Select the fund in each employee record.');}catch(e){setMessage(apiError(e));}finally{setBusy(false);}}
 return <section className="pay-panel" id="super-funds"><h3 className="font-bold text-lg">Super funds</h3><p className="text-sm my-3">Maintain fund names and USIs once for the company. Employees select from this list and retain their own member numbers. Changes here do not rewrite employee selections or past pay runs.</p>{message&&<p role="status">{String(message)}</p>}{data&&<><div className="space-y-3">{data.items.map((f,i)=><div className="border rounded-xl p-3" key={i}><FundRecognition check={checks[i]}/><div className="grid sm:grid-cols-3 gap-3"><label>Fund name<input aria-label={`Fund name ${i+1}`} disabled={!edit||busy} className="border rounded p-2 w-full" value={f.name} maxLength={160} onChange={e=>patch(i,'name',e.target.value)}/></label><label>Fund USI<input aria-label={`Fund USI ${i+1}`} disabled={!edit||busy} className="border rounded p-2 w-full" value={f.usi} maxLength={32} onChange={e=>patch(i,'usi',e.target.value)}/></label><label className="self-center"><input disabled={!edit||busy} type="checkbox" checked={f.active} onChange={e=>patch(i,'active',e.target.checked)}/> Available for selection</label></div><button type="button" className="pay-outline mt-3" disabled={busy||!f.name.trim()||!f.usi.trim()} onClick={()=>check(i)}>Check fund recognition</button>{checks[i]&&<div role="status" className="text-sm mt-2"><strong>{checks[i].error||({matched:'Fund name matches this USI',name_mismatch:'Recorded fund name does not match this USI',not_found:'USI not found in the official register',inactive:'USI is outside its recorded effective dates'}[checks[i].status])}</strong>{checks[i].matches?.map((m,j)=><p key={j}>{m.fund_name} / {m.product_name} / {m.usi}{m.restricted?' / Contact the fund about contribution restrictions':''}</p>)}<p>{checks[i].note}</p></div>}</div>)}</div>{!data.items.length&&<p>No shared funds recorded yet.</p>}<div className="flex gap-3 mt-3"><button type="button" className="pay-outline" disabled={!edit||busy} onClick={()=>{setData(d=>({...d,items:[...d.items,{name:'',usi:'',active:true}]}));setDirty(true);}}>Add super fund</button><button type="button" className="pay-gold" disabled={!edit||busy||!dirty} onClick={save}>Save super funds</button></div></>}</section>;
}

function FundRecognition({check}){
 const restricted=check?.matches?.some(m=>m.restricted);
 const matched=check?.status==='matched'&&!check.error;
 const failed=check&&!matched&&!check.error;
 const label=check?.error?'Check unavailable':matched?(restricted?'Recognised — restrictions apply':'Recognised'):failed?({name_mismatch:'Name does not match USI',not_found:'USI not recognised',inactive:'Inactive USI'}[check.status]||'Needs review'):'Not checked';
 const colour=matched&&!restricted?'bg-green-100 text-green-900 border-green-300':failed?'bg-red-100 text-red-900 border-red-300':'bg-amber-100 text-amber-900 border-amber-300';
 return <div className="mb-3" role="status"><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-sm font-semibold ${colour}`}><span aria-hidden="true">{matched&&!restricted?'✓':failed?'!':'●'}</span>{label}</span>{check?.checked_at&&<span className="ml-2 text-xs">Checked {new Date(check.checked_at).toLocaleString('en-AU',{timeZone:'Australia/Hobart'})}</span>}<p className="text-xs mt-2">Recognition checks the official fund name and USI. It does not confirm employee membership or acceptance of a payment.</p></div>;
}
