import PayEarningRules from './PayEarningRules';
import React,{useState,useEffect} from 'react';
import api,{apiError} from '../../lib/api';
import PayrollBankPanel from './PayrollBankPanel';
export default function PayrollRuleSettings(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{api.get('/payroll/workbench/calculation/settings').then(r=>setData(r.data)).catch(()=>setMessage('Could not load pay calculation defaults'));},[]);
 async function save(){setBusy(true);try{const r=await api.put('/payroll/workbench/calculation/settings',data);setData(r.data);setMessage('Calculation defaults saved for new pay runs. Saved runs keep their reviewed rules.');}catch(e){setMessage(apiError(e)||'Could not save defaults');}finally{setBusy(false);}}
 return <div className="space-y-4 mb-5"><section className="pay-panel" id="shift-rules"><h3>Shift rules and meal allowances</h3><p>Set the reviewed multipliers here. Employee rates and employment types are under Employee settings.</p>{data&&<><p className="text-sm my-3">First {data.rules.daily_ordinary_hours} paid hours at base rate, next 2 at {data.rules.ot1_multiplier} times, then {data.rules.ot2_multiplier} times. Weekday work before 6 am or from 6 pm uses {data.rules.night_multiplier} times; public holiday work uses {data.rules.holiday_work_multiplier} times. Saturday currently uses overtime tier 1 for all hours and Sunday uses tier 2; award-specific Saturday thresholds are not implemented. Check these rules against the employee’s award or agreement. Rates do not stack. One meal allowance at 10 paid hours and a second at 14.</p><p className="text-sm my-3">A night shift replacing an ordinary day shift accrues leave on up to {data.rules.daily_ordinary_hours} ordinary hours per shift day, within the employee's ordinary weekly hours. Casual employees do not accrue paid annual or sick leave. Actual shift times and replacement-shift selection are entered in the pay run.</p><div className="grid sm:grid-cols-3 gap-3 my-4">{[['ot1_multiplier','Overtime tier 1 multiplier',1],['ot2_multiplier','Overtime tier 2 multiplier',1],['super_percent','Super contribution %',12],['meal_allowance','Meal allowance per meal $',0],['night_multiplier','Weekday night multiplier',2],['holiday_work_multiplier','Public holiday worked multiplier',2.5]].map(([k,l,min])=><label className="text-sm" key={k}>{l}<input type="number" step="any" min={min} className="border rounded p-2 block w-full" value={data.rules[k]??''} onChange={e=>setData({...data,rules:{...data.rules,[k]:k==='meal_allowance'&&e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div><label className="block text-sm mb-3">Meal allowance tax treatment<select className="border rounded p-2 block" value={data.rules.meal_tax_treatment||"unconfirmed"} onChange={e=>setData({...data,rules:{...data.rules,meal_tax_treatment:e.target.value}})}><option value="unconfirmed">Choose after checking payroll treatment</option><option value="taxable">Taxable</option><option value="exempt">Exempt from withholding — reviewed</option></select></label><PayEarningRules rules={data.rules.earning_rules||[]} disabled={busy} onChange={earning_rules=>setData({...data,rules:{...data.rules,earning_rules}})}/><button type="button" className="pay-gold" disabled={busy} onClick={save}>Save calculation defaults</button></>}{message&&<p role="status" className="pay-notice">{typeof message==='string'?message:JSON.stringify(message)}</p>}</section><PayrollBankPanel mode="employer" workers={[]}/></div>;
}
