import React,{useEffect,useState} from 'react';
import api from '../../lib/api';
import PayrollPayslip from './PayrollPayslip';
export default function PayrollLifecycle({week,revision,dirty,onReload,onLocked}) {
 const [data,setData]=useState(null),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(''),[worker,setWorker]=useState('');
 useEffect(()=>{let active=true;setData(null);api.get(`/payroll/workbench/${week}/lifecycle`).then(({data:d})=>{if(active){setData(d);onLocked(d.status==='finalized');}}).catch(()=>{if(active)setMessage('Run status unavailable. Reload before making changes.');});return()=>{active=false;};},[week,revision,onLocked]);
 async function transition(action){setBusy(true);setMessage('');try{await api.post(`/payroll/workbench/${week}/${action}`,{revision,reason});const response=await api.get(`/payroll/workbench/${week}/lifecycle`);setData(response.data);onLocked(response.data.status==='finalized');await onReload(week);setReason('');setMessage(action==='finalize'?'Run locked. No payments, payslips, super or STP were sent.':'Correction opened. The previous finalised record has been preserved.');}catch(e){setMessage(typeof e.response?.data?.detail==='string'?e.response.data.detail:'Could not change run status');}finally{setBusy(false);}}
 const snapshot=data?.finalizations.find(r=>String(r.revision)===version),rows=snapshot?.report.rows||[],row=rows.find(r=>r.worker_id===worker)||rows[0];
 return <section className="border rounded-xl p-4 my-4" aria-label="Pay-run control"><h3 className="font-bold">Pay-run control — {data?.status==='finalized'?'Locked':'Open worksheet'}</h3>
 <p className="text-sm my-2">Finalising locks the reviewed worksheet and saves its figures and employer branding. It does not confirm wages paid, issue payslips, post leave balances or submit STP/super.</p>
 {data?.status==='finalized'?<><label className="text-sm block">Correction reason<textarea className="border rounded p-2 w-full block" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||!reason.trim()} className="border rounded p-2 mt-2 disabled:opacity-40" onClick={()=>transition('reopen')}>Open correction</button></>:<button type="button" disabled={busy||dirty||!revision||!data} className="border rounded p-2 disabled:opacity-40" onClick={()=>transition('finalize')}>Finalise reviewed run</button>}
 {message&&<p role="status" className="text-sm my-2">{message}</p>}
 {!!data?.finalizations.length&&<details className="mt-3"><summary>Finalised versions</summary><label className="text-sm">Finalised revision<select className="border rounded p-2 m-2" value={version} onChange={e=>setVersion(e.target.value)}><option value="">Select…</option>{data.finalizations.map(r=><option key={r.revision} value={r.revision}>Revision {r.revision} · {r.at}</option>)}</select></label>{row&&<><label className="text-sm">Finalised employee<select className="border rounded p-2 m-2" value={row.worker_id} onChange={e=>setWorker(e.target.value)}>{rows.map(r=><option key={r.worker_id} value={r.worker_id}>{r.name}</option>)}</select></label><PayrollPayslip row={row} sheet={snapshot.worksheet} week={week} branding={snapshot.branding} printable={false}/></>}
 <ul className="text-xs mt-2">{data.events.map((e,i)=><li key={i}>{e.at} · {e.action} · revision {e.revision} · {e.by}{e.reason?` · ${e.reason}`:''}</li>)}</ul></details>}
 </section>;
}
