import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
export default function PayrollAccess(){
 const [users,setUsers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const {data}=await api.get('/payroll/workbench/access/list');setUsers(data.users);}catch(e){setError(apiError(e)||'Only the payroll owner can manage access.');}}
 useEffect(()=>{load();},[]);
 async function change(person,level){if(!window.confirm(`Set payroll access for ${person.name||person.email} to ${level}?`))return;setBusy(true);setError('');try{await api.put(`/users/${person.id}/payroll-access`,{level});await load();}catch(e){setError(apiError(e)||'Could not change access');}finally{setBusy(false);}}
 return <section className="pay-panel"><h2>Manage payroll access</h2><p className="my-3">Only the payroll owner can authorise or remove access. View only allows payroll reports and records to be read; view and edit also allows payroll preparation. Access applies to both divisions.</p><p className="my-3">For a new accountant, first create their administrator account in <Link className="underline" to="/app/settings/users">Users &amp; Permissions</Link>, then grant access here. Creating an account does not grant payroll access.</p>{error&&<p role="alert">{String(error)}</p>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Name','Email','Payroll access','Last changed','Change access'].map(x=><th key={x} className="text-left p-3">{x}</th>)}</tr></thead><tbody>{users.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.name||'—'}</td><td>{p.email}</td><td>{({none:'No access',view:'View only',edit:'View and edit',owner:'Owner — full access'})[p.level]}</td><td>{p.updated_at?new Date(p.updated_at).toLocaleDateString('en-AU'):'—'}</td><td>{p.owner?'Owner access retained':<select aria-label={`Payroll access for ${p.email}`} disabled={busy} value={p.level} onChange={e=>change(p,e.target.value)} className="border rounded p-2"><option value="none">No access</option><option value="view">View only</option><option value="edit">View and edit</option></select>}</td></tr>)}</tbody></table></div></section>;
}
