import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
const actions=[['primary',"Employee's primary pay category"],['annual','Annual leave request'],['personal','Sick / carer leave request'],['unpaid','Unpaid leave request']];
const descriptions={primary:'Uses each employee’s saved ordinary rate and the global overtime rules.',annual:'Request and approve annual leave, then allocate approved hours in the pay run.',personal:'Request and approve sick / carer leave, then allocate approved hours in the pay run.',unpaid:'Request and approve unpaid leave. No paid earnings are added.'};
export default function PayrollWorkTypes(){
 const can=useCan(),edit=can('payroll','edit');
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 async function load(){try{setData((await api.get('/payroll/employee-records/configuration/work-types')).data);setDirty(false);}catch(e){setMessage(apiError(e));}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function patch(id,key,value){setData(d=>({...d,items:d.items.map(i=>i.id===id?{...i,[key]:value}:i)}));setDirty(true);}
 async function save(){setBusy(true);setMessage('');try{setData((await api.put('/payroll/employee-records/configuration/work-types',data)).data);setDirty(false);setMessage('Global work-type mappings saved. These apply to new selections across all employees.');}catch(e){setMessage(apiError(e));}finally{setBusy(false);}}
 return <section className="pay-panel" id="work-types"><h3 className="font-bold text-lg">Global work types and pay mappings</h3><p className="text-sm my-3">Set up each work type once for the whole company. “Employee's primary pay category” uses the selected worker's own saved rate; the same mapping applies to all employees.</p><p className="text-sm my-3">Work types linked to ordinary pay appear on phone timesheets and office approvals. Leave mappings use Leave Requests. Existing submitted entries and saved pay runs keep their history. Allowances and specific pay-category rates are not automatically assigned by these mappings yet.</p><div className="flex flex-wrap gap-4 my-3 text-sm"><Link className="underline" to="/app/pay/employees">Employee rates</Link><a className="underline" href="#shift-rules">Global overtime and meal rules</a><Link className="underline" to="/app/leave">Leave requests and approvals</Link></div>{message&&<p role="status">{String(message)}</p>}{data&&<><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Name</th><th>Pay or leave mapping</th><th>Available</th></tr></thead><tbody>{data.items.map(i=><tr key={i.id} className="border-b"><td className="p-2"><input aria-label={`Name for ${i.name}`} disabled={!edit||busy} className="border rounded p-2 w-full" maxLength={100} value={i.name} onChange={e=>patch(i.id,'name',e.target.value)}/></td><td className="p-2"><select aria-label={`Pay mapping for ${i.name}`} disabled={!edit||busy} className="border rounded p-2 w-full" value={i.action} onChange={e=>patch(i.id,'action',e.target.value)}>{actions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><p className="text-xs mt-2">{descriptions[i.action]}</p></td><td className="p-2"><input aria-label={`Enable ${i.name}`} disabled={!edit||busy} type="checkbox" checked={i.active} onChange={e=>patch(i.id,'active',e.target.checked)}/></td></tr>)}</tbody></table></div><div className="flex gap-3 mt-3"><button type="button" className="pay-outline" disabled={!edit||busy} onClick={()=>{setData(d=>({...d,items:[...d.items,{id:`work-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:'New work type',action:'primary',active:true}]}));setDirty(true);}}>Add work type</button><button type="button" className="pay-gold" disabled={!edit||busy||!dirty} onClick={save}>Save work types</button></div></>}</section>;
}
