import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
export default function PayrollWorkTypes(){
 const can=useCan(),edit=can('payroll','edit');
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 async function load(){try{setData((await api.get('/payroll/employee-records/configuration/work-types')).data);setDirty(false);}catch(e){setMessage(apiError(e));}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function patch(id,key,value){setData(d=>({...d,items:d.items.map(i=>i.id===id?{...i,[key]:value}:i)}));setDirty(true);}
 async function save(){setBusy(true);setMessage('');try{setData((await api.put('/payroll/employee-records/configuration/work-types',data)).data);setDirty(false);setMessage('Work types saved.');}catch(e){setMessage(apiError(e));}finally{setBusy(false);}}
 return <section className="pay-panel"><h3 className="font-bold text-lg">Work Types</h3><p className="text-sm my-3">Choose work types on phone timesheets and office approvals. Work entries use the employee's saved pay rates and overtime rules. A work type label does not add an allowance. Leave types use the existing Leave Requests approval process.</p>{message&&<p role="status">{String(message)}</p>}{data&&<><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Name</th><th>Action</th><th>Available</th></tr></thead><tbody>{data.items.map(i=><tr key={i.id} className="border-b"><td className="p-2"><input aria-label={`Name for ${i.name}`} disabled={!edit||busy} className="border rounded p-2 w-full" maxLength={100} value={i.name} onChange={e=>patch(i.id,'name',e.target.value)}/></td><td className="p-2">{i.action==='primary'?"Employee's primary pay category":i.action==='annual'?'Annual leave request':i.action==='personal'?'Sick / carer leave request':'Unpaid leave request'}</td><td className="p-2"><input aria-label={`Enable ${i.name}`} disabled={!edit||busy} type="checkbox" checked={i.active} onChange={e=>patch(i.id,'active',e.target.checked)}/></td></tr>)}</tbody></table></div><div className="flex gap-3 mt-3"><button type="button" className="pay-outline" disabled={!edit||busy} onClick={()=>{setData(d=>({...d,items:[...d.items,{id:`work-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:'New work type',action:'primary',active:true}]}));setDirty(true);}}>Add work type</button><button type="button" className="pay-gold" disabled={!edit||busy||!dirty} onClick={save}>Save work types</button></div></>}</section>;
}
