import React,{useState} from 'react';
import api,{apiError} from '../../lib/api';

export default function PayrollTimesheetDays({source,onChanged,onRefresh}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[clients,setClients]=useState([]),[matching,setMatching]=useState(null),[client,setClient]=useState(''),[job,setJob]=useState('');
 const days=source?.days||[];
 async function decide(action){
  const ids=days.filter(d=>action==='approve'?d.status==='submitted':['submitted','approved'].includes(d.status)).map(d=>d.id);
  if(!ids.length)return;
  const reason=action==='reject'?window.prompt('Reason for sending these days back to the worker:'):'';
  if(reason===null)return;
  if(action==='approve'&&!window.confirm('Approve the submitted days shown for this employee?'))return;
  setBusy(true);setMessage('');
  try{await api.post(`/payroll/timesheets/${action}`,{ids,reason});await onChanged();setMessage(action==='approve'?'Days approved. Refresh the submitted hours, then review this employee again.':'Days returned to the worker. Refresh the submitted hours to remove them from this draft pay run.');}catch(e){setMessage(apiError(e)||'Could not update days');}finally{setBusy(false);}
 }
 async function openMatch(day,segment){setBusy(true);try{const {data}=await api.get('/payroll/time-catalog');setClients(data.clients);setMatching({day,segment});setClient('');setJob('');}catch(e){setMessage(apiError(e)||'Could not load clients');}finally{setBusy(false);}}
 async function match(){setBusy(true);try{await api.post(`/payroll/timesheets/${matching.day.id}/segments/${matching.segment.id}/match`,{revision:matching.day.revision||0,client_key:client,job_id:job});setMatching(null);await onChanged();setMessage('Client matched. Refresh submitted hours to use the updated source record.');}catch(e){setMessage(apiError(e)||'Could not match client');}finally{setBusy(false);}}
 const btn='border rounded-lg bg-white px-3 py-2 text-sm disabled:opacity-40';
 return <section className="bg-indigo-50 rounded-lg p-3"><h4 className="font-semibold">Phone-submitted days</h4>
 {days.length?<div className="overflow-x-auto"><table className="w-full text-sm my-2"><thead><tr className="text-left"><th>Date</th><th>Clients / jobs</th><th>Hours</th><th>Status</th></tr></thead><tbody>{days.map(d=><tr key={d.id} className="border-t align-top"><td className="py-2 whitespace-nowrap pr-2">{d.date}<span className="block text-xs">{d.kind}</span></td><td className="py-2 pr-2">{d.segments?.length?<><div>{[...new Set(d.segments.map(s=>s.client_name))].join(', ')}</div><div className="text-xs">{d.job_ref&&`Jobs: ${d.job_ref}`}</div><details className="my-1"><summary className="cursor-pointer text-indigo-700">View {d.segments.length} time entries</summary>{d.segments.map(s=><div key={s.id} className="border-l-2 pl-2 my-2"><strong>{s.client_name}</strong>{s.job_ref&&` · Job ${s.job_ref}`}<div>{s.start}–{s.finish} · {s.break_minutes} min break</div>{s.notes&&<div>{s.notes}</div>}{s.category==='unmatched'&&<button type="button" className={btn} disabled={busy} onClick={()=>openMatch(d,s)}>Match client in Simpro</button>}</div>)}</details></>:<>{d.site_name||'No client recorded'}{d.job_ref&&` · Job ${d.job_ref}`}</>}{d.notes&&<div className="text-xs">{d.notes}</div>}{d.allowances?.length>0&&<div className="text-xs">Allowances: {d.allowances.map(a=>`${a.code}: ${a.qty??a.units??a.quantity??''}`).join(', ')}</div>}</td><td className="py-2 pr-2 whitespace-nowrap">{Number(d.hours).toFixed(2)}</td><td className="py-2">{d.status}</td></tr>)}</tbody></table></div>:<p className="text-sm my-2">No submitted days this week. The worker can enter time in My Timesheet on their phone.</p>}
 {source?.notes?.map((n,i)=><p className="text-sm text-amber-900" key={i}>{n}</p>)}
 <div className="flex gap-2 flex-wrap"><button type="button" className={btn} disabled={busy||!days.some(d=>d.status==='submitted')} onClick={()=>decide('approve')}>Approve submitted days</button><button type="button" className={btn} disabled={busy||!days.some(d=>['submitted','approved'].includes(d.status))} onClick={()=>decide('reject')}>Send days back to worker</button><button type="button" className={btn} disabled={busy} onClick={onRefresh}>Refresh submitted hours for this employee</button></div>
 {matching&&<fieldset disabled={busy} className="bg-white border rounded-lg p-3 mt-3 space-y-2"><legend className="font-semibold">Match “{matching.segment.client_name}”</legend><label className="block text-sm">Simpro client<select className="block border p-2 w-full" value={client} onChange={e=>{setClient(e.target.value);setJob('');}}><option value="">Choose client</option>{clients.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select></label><label className="block text-sm">Job<select className="block border p-2 w-full" value={job} onChange={e=>setJob(e.target.value)}><option value="">No particular job</option>{clients.find(c=>c.key===client)?.jobs.map(j=><option key={j.id} value={j.id}>{j.number} · {j.name}</option>)}</select></label><button type="button" className={btn} disabled={!client} onClick={match}>Save client match</button> <button type="button" className={btn} onClick={()=>setMatching(null)}>Cancel</button></fieldset>}
 {!!message&&<p role="status" className="text-sm mt-2">{message}</p>}<p className="text-xs mt-2">Each day totals all its entries. Overtime is estimated once for the whole day; review allowances, leave and missing days before approving pay.</p>
 </section>;
}
