import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
const empty={provider:'',requirements:'',receipt_method:'not_connected',accepted_status:''};
export default function PayrollPortalRequirements(){
 const can=useCan(),[labels,setLabels]=useState({}),[forms,setForms]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api.get('/payroll/workbench/portals/requirements').then(({data})=>{setLabels(data.labels);setForms(data.portals);}).catch(e=>setMessage(apiError(e)||'Could not load portal requirements'));},[]);
 function edit(key,field,value){setForms({...forms,[key]:{...empty,...forms[key],[field]:value}});}
 async function save(key){setBusy(true);try{const f={...empty,...forms[key]};await api.put(`/payroll/workbench/portals/requirements/${key}`,Object.fromEntries(Object.keys(empty).map(k=>[k,f[k]])));setMessage(`${labels[key]} requirements saved. The provider adapter is not connected yet.`);}catch(e){setMessage(apiError(e)||'Could not save');}finally{setBusy(false);}}
 return <section className="pay-panel mt-4"><h2>Portal feedback requirements</h2><p className="my-3">Record how each portal will acknowledge reports. These settings prepare the connection; a tested provider adapter is still required. Do not enter passwords, API keys or employee details.</p>{Object.entries(labels).map(([key,label])=>{const f={...empty,...forms[key]};return <details key={key} className="border rounded p-3 my-2"><summary className="font-semibold">{label} · adapter not connected</summary><div className="grid sm:grid-cols-2 gap-3 mt-3"><label>Provider<input className="border rounded p-2 w-full" maxLength={160} disabled={!can('payroll','edit')} value={f.provider} onChange={e=>edit(key,'provider',e.target.value)}/></label><label>Planned feedback method<select className="border rounded p-2 w-full" disabled={!can('payroll','edit')} value={f.receipt_method} onChange={e=>edit(key,'receipt_method',e.target.value)}><option value="not_connected">Not selected</option><option value="webhook_planned">Provider webhook</option><option value="polling_planned">Poll provider API</option><option value="manual">Office verification</option></select></label><label>Provider status meaning accepted<input className="border rounded p-2 w-full" maxLength={200} disabled={!can('payroll','edit')} value={f.accepted_status} onChange={e=>edit(key,'accepted_status',e.target.value)}/></label><label>Connection requirements<textarea className="border rounded p-2 w-full" maxLength={4000} disabled={!can('payroll','edit')} value={f.requirements} onChange={e=>edit(key,'requirements',e.target.value)}/></label></div>{can('payroll','edit')&&<button className="pay-gold mt-3" disabled={busy} onClick={()=>save(key)}>Save {label} requirements</button>}</details>;})}{message&&<p role="status">{String(message)}</p>}</section>;
}
