import React from 'react';
import DateField from './DateField';
const input='border rounded p-2 w-full';
export default function PayrollShiftInputs({row,source,week,onChange}){
 const change=shifts=>onChange({...row,shifts,entry:{...row.entry,hours_reviewed:false,super_reviewed:false}});
 const patch=(i,k,v)=>change(row.shifts.map((s,n)=>n===i?{...s,[k]:v}:s));
 const add=()=>change([...(row.shifts||[]),{date:week,start:'07:00',finish:'15:06',break_minutes:30,break_start:'12:00',next_day:false,public_holiday:false,replacement_day_shift:false}]);
 const load=()=>{if(row.shifts?.length&&!window.confirm('Replace these shift entries with submitted phone times?'))return;change((source?.days||[]).filter(d=>d.kind==='work').flatMap(d=>(d.segments?.length?d.segments:[d]).map(s=>({date:d.date,start:s.start||'',finish:s.finish||'',break_minutes:s.break_minutes||0,break_start:s.break_start||null,next_day:false,public_holiday:false,replacement_day_shift:false}))));};
 return <section className="border rounded-xl p-4"><h4 className="font-semibold">Shift rules and meal allowances</h4><p className="text-sm my-2">First 7.6 paid hours at base rate, next 2 at 1.5×, remainder at 2×. Weekday time before 6 am or from 6 pm is 2×; public-holiday work is 2.5×. Rates do not stack. Meals: one at 10 paid hours, another at 14. Saturday/Sunday rules remain unchanged.</p><div className="flex gap-3"><button type="button" className="pay-outline" onClick={load}>Use submitted shift times</button><button type="button" className="pay-outline" onClick={add}>Add shift</button></div>{row.shifts!==null&&row.shifts!==undefined&&<><p className="text-xs my-2">Calculated hours replace the worked-hour totals. Enter the actual break start when a shift crosses a day/night rate boundary. Split shifts at a public-holiday boundary; use the shift start date for overnight work.</p>{row.shifts.map((s,i)=><div key={i} className="border-t py-3"><div className="grid sm:grid-cols-5 gap-2"><label>Date<DateField className={input} value={s.date} onChange={e=>patch(i,'date',e.target.value)}/></label>{[['start','Start'],['finish','Finish'],['break_start','Break start']].map(([k,l])=><label key={k}>{l}<input type="time" onInput={e=>patch(i,k,e.currentTarget.value||null)} className={input} value={s[k]||''} onChange={e=>patch(i,k,e.target.value||null)}/></label>)}<label>Unpaid break minutes<input type="number" min="0" max="600" className={input} value={s.break_minutes} onChange={e=>patch(i,'break_minutes',Number(e.target.value))}/></label></div><div className="flex flex-wrap gap-4 mt-2">{[['next_day','Finish next day'],['public_holiday','Public holiday worked'],['replacement_day_shift','Night shift replaces ordinary day shift']].map(([k,l])=><label key={k} className="text-sm"><input type="checkbox" checked={!!s[k]} onChange={e=>patch(i,k,e.target.checked)}/> {l}</label>)}<button type="button" className="underline" onClick={()=>change(row.shifts.filter((_,n)=>i!==n))}>Remove shift</button></div></div>)}<p className="text-xs">Replacement shifts accrue leave on up to 7.6 ordinary hours per shift day, within the employee’s ordinary weekly hours. Check the calculation before saving.</p></>}</section>;
}
