import React,{useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
import DateField from './DateField';
import {division,sortWorkers} from './PayrollEmployeeSettings';
export default function PayrollExtraRun({week,payday}){
 const [open,setOpen]=useState(false),[workers,setWorkers]=useState([]),[selected,setSelected]=useState([]),[paid,setPaid]=useState(payday),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const navigate=useNavigate();
 useEffect(()=>{if(open){setPaid(payday);api.get('/payroll/workbench/employees/list').then(r=>setWorkers(sortWorkers(r.data.workers))).catch(e=>setError(apiError(e)));}},[open,payday]);
 async function create(e){e.preventDefault();setBusy(true);setError('');try{const {data}=await api.post('/payroll/workbench/out-of-cycle/create',{week,payday:paid,workers:selected,reason,payslip_message:message});navigate(`/app/pay/payroll?week=${encodeURIComponent(data.run_id)}`);}catch(e){setError(apiError(e)||'Could not create extra run');}finally{setBusy(false);}}
 return <><button type="button" className="pay-outline" disabled={!week} onClick={()=>setOpen(true)}>Start out-of-cycle pay</button>{open&&<div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-4"><form onSubmit={create} role="dialog" aria-modal="true" aria-label="Out-of-cycle pay" className="bg-white rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-auto"><h2 className="text-xl font-bold">Out-of-cycle pay</h2><p className="text-sm my-3">Extra payment for selected employees for the week starting {week}. The normal weekly run stays unchanged. Enter only additional amounts; phone hours and leave are not imported. PAYG requires a reviewed extra-payment calculation.</p><fieldset disabled={busy} className="space-y-3"><label className="block">Payment date<DateField required value={paid||''} onChange={e=>setPaid(e.target.value)} className="border rounded p-2 block"/></label><label className="block">Reason for extra payment<textarea required maxLength={500} className="border rounded p-2 w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="block">Payslip message (optional)<input maxLength={500} className="border rounded p-2 w-full" value={message} onChange={e=>setMessage(e.target.value)}/></label><input aria-label="Find employees for extra pay" className="border rounded p-2 w-full" placeholder="Find employees…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="max-h-64 overflow-auto border rounded p-3">{workers.filter(w=>w.name.toLowerCase().includes(search.toLowerCase())).map(w=><label key={w.id} className="flex gap-2 py-2"><input type="checkbox" checked={selected.includes(w.id)} onChange={e=>setSelected(e.target.checked?[...selected,w.id]:selected.filter(id=>id!==w.id))}/>{w.name}<small>{division(w)}</small></label>)}</div><p>{selected.length} selected</p>{error&&<p role="alert">{String(error)}</p>}<div className="flex gap-3"><button className="pay-gold" disabled={!selected.length||!reason.trim()}>Create extra run</button><button type="button" className="pay-outline" onClick={()=>setOpen(false)}>Cancel</button></div></fieldset></form></div>}</>;
}
