import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
import {useCan} from '../../lib/permissions';
export default function PayrollAwardSettings(){
 const can=useCan(),edit=can('payroll','edit'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 useEffect(()=>{api.get('/payroll/employee-records/configuration/awards').then(r=>setData(r.data)).catch(e=>setMessage(apiError(e)||'Could not load awards'));},[]);
 function patch(i,key,value){setData(d=>({...d,items:d.items.map((a,j)=>i===j?{...a,[key]:value}:a)}));setDirty(true);}
 async function save(){setBusy(true);setMessage('');try{setData((await api.put('/payroll/employee-records/configuration/awards',data)).data);setDirty(false);setMessage('Awards saved. They are available in Employee settings.');}catch(e){setMessage(apiError(e)||'Could not save awards');}finally{setBusy(false);}}
 return <section className="pay-panel" id="awards"><h3 className="font-bold text-lg">Awards</h3><p className="text-sm my-3">Add award names and codes once, then select them in Employee settings. Selecting an award does not automatically change pay rates or payroll rules. Existing employee selections remain unchanged when this list is edited.</p>{message&&<p role="status">{String(message)}</p>}{data&&<><fieldset disabled={!edit||busy} className="space-y-3">{data.items.map((a,i)=><div key={i} className="flex flex-wrap items-center gap-3 border rounded-xl p-3"><label className="flex-1 min-w-64">Award name and code<input aria-label={`Award name and code ${i+1}`} className="block border rounded p-2 w-full" value={a.name} maxLength={200} onChange={e=>patch(i,'name',e.target.value)}/></label><label><input type="checkbox" checked={a.active} onChange={e=>patch(i,'active',e.target.checked)}/> Available for selection</label></div>)}<div className="flex gap-3"><button type="button" className="pay-outline" onClick={()=>{setData(d=>({...d,items:[...d.items,{name:'',active:true}]}));setDirty(true);}}>Add award</button><button type="button" className="pay-gold" disabled={!dirty} onClick={save}>Save awards</button></div></fieldset></>}</section>;
}
