import React from 'react';
const money=v=>Number(v||0).toLocaleString('en-AU',{style:'currency',currency:'AUD'});
const input='border rounded p-2 w-full bg-white';
export default function PayrollCasualRates({profile,onChange,busy=false}){
 const rates=profile.casual_rates,allowances=profile.allowance_rates||[];
 const update=value=>onChange({...profile,...value,conditions_reviewed:false});
 const patch=(key,value)=>update({casual_rates:{...rates,[key]:value}});
 return <fieldset disabled={busy} className="border rounded-xl p-4 my-4"><h3>Pay rates and allowances</h3>{profile.employment_type==='casual'&&<><p className="text-sm my-2">Casual template: separate base pay, loading and final penalty rates. Final overrides already include any applicable loading; it is not added again.</p>{!rates?<button type="button" className="pay-outline" onClick={()=>update({pay_basis:'hourly',casual_rates:{base_rate:0,loading_percent:25,ot1:null,ot2:null,night:null,holiday_work:null}})}>Set up casual rate table</button>:<><div className="grid sm:grid-cols-3 gap-3"><label>Base hourly rate, before loading<input aria-label="Casual base hourly rate" className={input} type="number" min="0" step="0.00001" value={rates.base_rate} onChange={e=>patch('base_rate',Number(e.target.value))}/></label><label>Casual loading %<input className={input} type="number" min="0" max="100" step="0.01" value={rates.loading_percent} onChange={e=>patch('loading_percent',Number(e.target.value))}/></label><div>Ordinary rate including loading<strong className="block">{money(rates.base_rate*(1+rates.loading_percent/100))} / hour</strong></div></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr><th className="text-left p-2">Pay category</th><th>Final hourly rate override</th><th>Annual / sick leave</th></tr></thead><tbody>{[['ot1','Overtime — first tier'],['ot2','Overtime — second tier'],['night','Weekday night shift'],['holiday_work','Public holiday worked']].map(([key,label])=><tr key={key} className="border-t"><td className="p-2">{label}</td><td className="p-2"><input aria-label={`${label} final rate`} className={input} type="number" min="0" step="0.00001" placeholder="Use calculation rule" value={rates[key]??''} onChange={e=>patch(key,e.target.value===''?null:Number(e.target.value))}/></td><td className="p-2">No accrual</td></tr>)}</tbody></table></div><p className="text-xs mt-2">Blank overrides use the pay run’s multiplier on the loaded ordinary rate. Enter the final award/agreed rate where its loading treatment differs. Confirm the award/classification and rates below before using them.</p><button type="button" className="underline text-sm mt-2" onClick={()=>update({casual_rates:null,hourly_rate:rates.base_rate*(1+rates.loading_percent/100)})}>Use a single loaded hourly rate instead</button></>}</>}
 <h4 className="font-semibold mt-4">Allowance rates per unit</h4><p className="text-xs my-2">Set the rate here, then enter the quantity in the pay run. These are taxable additions and do not add worked hours or accrue leave. Use reimbursements for expense repayments. Super remains based on reviewed qualifying earnings.</p>{allowances.map((a,i)=><div className="grid sm:grid-cols-3 gap-2 my-2" key={a.code}><label>Allowance name<input className={input} maxLength={100} value={a.name} onChange={e=>update({allowance_rates:allowances.map((v,j)=>j===i?{...v,name:e.target.value}:v)})}/></label><label>Rate per unit $<input className={input} type="number" min="0" step="0.01" value={a.rate} onChange={e=>update({allowance_rates:allowances.map((v,j)=>j===i?{...v,rate:Number(e.target.value)}:v)})}/></label><button type="button" className="pay-outline" onClick={()=>update({allowance_rates:allowances.filter((_,j)=>j!==i)})}>Remove allowance</button></div>)}<button type="button" className="pay-outline" disabled={allowances.length>=20} onClick={()=>update({allowance_rates:[...allowances,{code:`allowance_${Date.now()}`,name:'',rate:0}]})}>Add allowance rate</button></fieldset>;
}
