import React,{useEffect,useState,useRef} from 'react';
import {useCan} from '../../lib/permissions';
import {Link} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
import DateField from './DateField';
import {cash,PayBadge} from './PayrollFlow';
import PayrollBankPanel from './PayrollBankPanel';
import PayrollIssuing from './PayrollIssuing';
import PayrollConnections from './PayrollConnections';
import PayrollHistory from './PayrollHistory';
export default function PayrollCompletion({week,sheet,report,workers,dirty,locked,mode="payment",onDownload}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[kind,setKind]=useState(''),[reference,setReference]=useState(''),[date,setDate]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[clients,setClients]=useState([]);
 async function refresh(){try{const {data:d}=await api.get(`/payroll/workbench/${week}/completion`);setData(d);}catch(e){setError(apiError(e)||'Could not load completion status');}}
 useEffect(()=>{refresh();api.get(`/payroll/workbench/${week}/submissions`).then(({data:d})=>{const totals={};for(const source of Object.values(d.workers))for(const day of source.days||[])for(const s of day.segments||[])totals[s.client_name]=(totals[s.client_name]||0)+Number(s.hours||0);setClients(Object.entries(totals).sort((a,b)=>b[1]-a[1]));}).catch(()=>{});},[week,sheet.revision]);
 async function record(){setBusy(true);setError('');try{const r=await api.post(`/payroll/workbench/${week}/completion/${kind}`,{revision:sheet.revision,reference,completed_date:date,confirmed});setData(r.data);setKind('');}catch(e){setError(apiError(e)||'Could not record result');}finally{setBusy(false);}}
 async function close(){setBusy(true);setError('');try{const r=await api.post(`/payroll/workbench/${week}/close-run`,{revision:sheet.revision,confirmed:true});setData(r.data);}catch(e){setError(apiError(e)||'Could not close run');}finally{setBusy(false);}}
 const can=useCan(),closing=useRef('');
 useEffect(()=>{const key=`${week}:${sheet.revision}`;if(data?.can_close&&!data.closed&&!dirty&&can('payroll','edit')&&closing.current!==key){closing.current=key;close();}},[data,dirty,week,sheet.revision]);
 const names={bank:'Wages paid in Westpac',stp:'STP accepted by the ATO through your reporting service',super:'Super received by employee funds',leave:'Leave balances reconciled in your current leave system',journal:'Accounting journal posted externally'};
 function open(k){setKind(k);setReference('');setDate('');setConfirmed(false);}
 const recordButton=k=><button className="pay-outline mt-3" disabled={!locked||dirty||!!data?.record?.[k]||data?.closed} onClick={()=>open(k)}>Record external result</button>;
 return <div>{error&&<p role="alert" className="pay-notice">{typeof error==='string'?error:JSON.stringify(error)}</p>}<div className="pay-complete-banner"><strong>{data?.closed?'Pay run closed':locked?'Approved and locked':'Approval required'}</strong><p>{sheet.rows.length} employees · Net {cash(report?.totals.net)} · PAYG {cash(report?.totals.payg)} · Super {cash(report?.totals.super)}</p><p>{data?.closed?'Closed against recorded external evidence. This app has not independently confirmed bank, ATO or fund receipts.':'Track payment, payslip dispatch, ATO acceptance and super fund receipt separately.'}</p></div>
 <div className="pay-grid-equal">{mode==='payment'&&<><section className="pay-panel"><div className="flex justify-between"><h3>Pay staff</h3><PayBadge tone={data?.record.bank||data?.issued?'good':'warn'}>{data?.record.bank||data?.issued?'Recorded paid':'Not confirmed'}</PayBadge></div><p>Prepare the net-wage file, then upload and authorise it in Westpac. Downloading a file does not pay employees.</p><PayrollBankPanel mode="batch" week={week} workers={workers} worksheetSaved={locked&&!dirty&&sheet.reviewed&&sheet.revision>0}/>{recordButton('bank')}</section>
 <section className="pay-panel"><div className="flex justify-between"><h3>Send payslips</h3><PayBadge tone={data?.emails.total&&data.emails.accepted===data.emails.total?'good':'info'}>{data?.emails.accepted||0} / {data?.emails.total||0} accepted by email service</PayBadge></div><p>Send private payslips after confirming payment. Email-service acceptance does not confirm receipt in the employee’s inbox.</p><PayrollIssuing week={week} revision={sheet.revision} workers={workers} dirty={dirty} locked={locked} onCompleted={refresh}/><button className="pay-outline mt-3" onClick={refresh}>Refresh dispatch status</button></section>
 </>}{mode==='reports'&&<section className="pay-panel"><div className="flex justify-between"><h3>Report to the ATO</h3><PayBadge tone={data?.record.stp?'good':'warn'}>{data?.record.stp?'External receipt recorded':'Not connected'}</PayBadge></div><p>Lodge STP through your reporting service on or before payday. The PAYG report below supports reconciliation; it is not an STP file.</p><button className="pay-secondary mt-3 mr-2" disabled={dirty||!sheet.revision} onClick={()=>onDownload('payg')}>Download PAYG report</button>{recordButton('stp')}</section>}
 {mode==='super'&&<section className="pay-panel"><div className="flex justify-between"><h3>Pay super</h3><PayBadge tone={data?.record.super?'good':'warn'}>{data?.record.super?'Fund receipt recorded':'Not connected'}</PayBadge></div><p>Use your clearing house. This CSV is a review report, not a SuperStream submission.</p><p className="mt-3 text-sm">From 1 July 2026, pay super on payday. Funds generally must receive it within 7 business days after payday; extended timeframes can apply. Confirm fund receipt, allowing for clearing-house processing.</p><a className="underline text-sm" href="https://softwaredevelopers.ato.gov.au/PaydaySuper" target="_blank" rel="noopener noreferrer">ATO Payday Super guidance</a><button className="pay-secondary mt-3 mr-2" disabled={dirty||!sheet.revision} onClick={()=>onDownload('super')}>Download super report</button>{recordButton('super')}</section>}</div>
 {mode==='reports'&&<><div className="pay-grid-equal"><section className="pay-panel"><h3>What happened</h3><p>{locked?'Run locked':'Run remains open'} · revision {sheet.revision}</p>{Object.entries(data?.record||{}).filter(([k])=>names[k]).map(([k,v])=><div key={k} className="border-b py-3"><strong className="text-sm">{names[k]}</strong><p>{v.completed_date} · {v.reference}</p><small>Recorded by {v.recorded_by} · {v.recorded_at}</small></div>)}{data?.closed&&<p className="pay-success mt-3">Closed {data.record.closed_at}</p>}<PayrollHistory week={week} revision={sheet.revision}/></section><section className="pay-panel"><h3>Hours by client</h3><p>Recorded phone entries for this week; not a costed Simpro journal.</p>{clients.length?clients.map(([name,h])=><div key={name} className="text-sm mt-4"><div className="flex justify-between"><span>{name}</span><strong>{h.toFixed(1)} h</strong></div><div className="pay-client-bar"><i style={{width:`${Math.max(2,h/clients[0][1]*100)}%`}}/></div></div>):<p className="mt-4">No client time entries for this run.</p>}</section><section className="pay-panel"><h3>Reconcile leave balances</h3><p>The app shows projected leave. Reconcile and post leave in your current leave system before recording completion here.</p><button className="pay-secondary mt-3 mr-2" disabled={dirty||!sheet.revision} onClick={()=>onDownload('leave')}>Download leave report</button>{recordButton('leave')}</section><section className="pay-panel"><h3>Accounts and job costing</h3><p>Xero and costed Simpro posting are not connected. Record your external journal reference if used.</p>{recordButton('journal')}</section></div><section className="pay-panel mt-5"><h3>Completion checks</h3>{data?.blockers.length?<ul className="list-disc pl-5 text-sm space-y-2">{data.blockers.map(b=><li key={b}>{b}</li>)}</ul>:<p>Required evidence is recorded. Check the original receipts and payroll reconciliation before closing.</p>}<p className="text-sm mt-3">This run closes automatically when the payment, payslip, STP, super and leave evidence is complete. No separate close step is required.</p><button className="pay-outline mt-3" onClick={()=>{closing.current='';refresh();}}>Refresh checks</button></section></>}
 {kind&&<section className="pay-panel mt-5" role="region" aria-label="Record external result"><h3>{names[kind]}</h3><p>This records evidence you have checked outside Paneltec Pay. It does not make a payment or lodge a report.</p><fieldset disabled={busy} className="space-y-3 mt-4"><label className="block text-sm">Completed / received date<DateField className="border rounded p-2 block" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block text-sm">Receipt or reconciliation reference<input className="border rounded p-2 block w-full" maxLength={300} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="block text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked the original receipt and it matches this run’s employees, amounts and revision.</label><button className="pay-outline mr-2" onClick={()=>setKind('')}>Cancel</button><button className="pay-gold" disabled={!confirmed||!date||!reference.trim()} onClick={record}>Save evidence</button></fieldset></section>}
 <div className="pay-actions"><Link className="pay-outline" to={`/app/pay/payroll?week=${week}`}>Back to pay run</Link></div></div>;
}
