import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
export default function PayrollBranding({onSaved}) {
 const [form,setForm]=useState(null),[workers,setWorkers]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api.get('/payroll/workbench/branding').then(({data})=>{setForm(data.settings);setWorkers(data.workers);}).catch(()=>setMessage('Branding settings unavailable.'));},[]);
 async function logo(key,file){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>200000){setMessage('Choose a PNG or JPEG up to 200 KB.');return;}const value=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});setForm(f=>({...f,[key]:{...f[key],logo:value}}));}
 async function save(){setBusy(true);try{const {data}=await api.put('/payroll/workbench/branding',form);setForm(data.settings);onSaved?.(data.settings);setMessage('Employer and division branding saved.');}catch(e){setMessage(apiError(e)||'Could not save branding');}finally{setBusy(false);}}
 return <details className="border rounded-xl p-4 mb-4"><summary className="font-semibold cursor-pointer">Payslip settings — employer and division logos</summary><p className="text-sm my-3">One legal employer appears on every statement. Simpro determines branding automatically: Traffic Control uses Viatec; every other employee uses Paneltec Civil. No manual assignment is needed.</p>{form&&<div className="space-y-4">
 <label className="block text-sm">Legal employer name<input className="border rounded p-2 block w-full" value={form.employer_name} onChange={e=>setForm({...form,employer_name:e.target.value})}/></label>
 <label className="block text-sm">Employer ABN (11 digits)<input className="border rounded p-2 block w-full" value={form.employer_abn} maxLength={11} onChange={e=>setForm({...form,employer_abn:e.target.value.replace(/\D/g,'')})}/></label>
 <div className="grid sm:grid-cols-2 gap-4">{['paneltec','viatec'].map(key=><div key={key} className="border rounded p-3"><label className="block text-sm">Division name<input className="border rounded p-2 w-full" value={form[key].name} onChange={e=>setForm({...form,[key]:{...form[key],name:e.target.value}})}/></label>{form[key].logo&&<img src={form[key].logo} alt={`${form[key].name} logo`} className="h-16 max-w-full object-contain my-2"/>}<label className="block text-sm mt-2">Upload {form[key].name} logo<input type="file" accept="image/png,image/jpeg" className="block w-full my-2" onChange={e=>logo(key,e.target.files?.[0]).catch(()=>setMessage('Could not read logo'))}/></label><button type="button" className="underline text-sm" onClick={()=>setForm({...form,[key]:{...form[key],logo:''}})}>Remove logo</button></div>)}</div>
 <h4 className="font-semibold">Simpro departments (read only)</h4><div className="max-h-72 overflow-auto">{workers.map(w=><div key={w.id} className="flex justify-between gap-2 border-b p-2 text-sm"><span>{w.name}<small className="block text-slate-500">{w.department||'No department recorded'}</small></span><span>{form[w.division]?.name}</span></div>)}</div>
 <button type="button" disabled={busy} onClick={save} className="border rounded-lg px-4 py-2 bg-indigo-900 text-white">Save payslip branding</button></div>}{message&&<p role="status" className="text-sm mt-3">{typeof message==='string'?message:JSON.stringify(message)}</p>}</details>;
}
