import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import api,{apiError} from '../../lib/api';
export default function PayrollAccess(){
 const [users,setUsers]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[level,setLevel]=useState('view'),[editing,setEditing]=useState(null);
 async function load(){try{const {data}=await api.get('/payroll/workbench/access/list');setUsers(data.users);return true;}catch(e){setError(apiError(e)||'Only the payroll owner can manage access.');return false;}}
 useEffect(()=>{load();},[]);
 async function change(person,next){if(!window.confirm(`${next==='none'?'Remove payroll access for':'Set payroll access to '+next+' for'} ${person.name||person.email}?`))return;setBusy(true);setError('');try{await api.put(`/users/${person.id}/payroll-access`,{level:next});await load();setAdding(false);setEditing(null);setMessage(next==='none'?'Payroll access removed. The approved admin and worker records are retained.':'Payroll access saved.');}catch(e){setError(apiError(e)||'Could not change access');}finally{setBusy(false);}}
 async function invite(person){if(!window.confirm(`Email a sign-in invitation to ${person.email}?`))return;setBusy(true);setError('');try{await api.post(`/payroll/workbench/access/${person.id}/invite`);await load();setMessage('Invitation processed through the app email service. Check Email outbox for delivery or Safe Mode status.');}catch(e){setError(apiError(e)||'Could not invite this user');}finally{setBusy(false);}}
 async function saveDetails(){setBusy(true);setError('');try{await api.patch(`/users/${editing.id}`,{name:editing.name,email:editing.email});await load();setEditing(null);setMessage('Approved user details updated.');}catch(e){setError(apiError(e)||'Could not update user details');}finally{setBusy(false);}}
 const members=users.filter(p=>p.owner||p.level!=='none');
 const available=users.filter(p=>!p.owner&&p.level==='none'&&p.status!=='disabled'&&`${p.name} ${p.email}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="pay-panel"><div className="flex justify-between flex-wrap gap-3"><h2>Manage payroll access</h2><div className="flex gap-2"><button className="pay-gold" disabled={busy} onClick={()=>{setAdding(true);setSelected('');}}>Add person / invite accountant</button><button className="pay-outline" disabled={busy} onClick={async()=>{if(await load()){setAdding(true);setSelected('');setMessage('Approved administrators refreshed. Select who to add and their access level.');}}}>Import from approved admin list</button></div></div><p className="my-3">Only the payroll owner can authorise or remove access. View only allows reports and payroll records; view and edit also allows preparation. Access covers both divisions. Removing a person revokes payroll access, without deleting their account or worker record.</p><p className="text-sm mb-3">An accountant must first be an approved administrator in <Link className="underline" to="/app/settings/users">Users &amp; Permissions</Link>. Import uses those existing accounts and does not grant everyone access.</p>{error&&<p role="alert">{String(error)}</p>}{message&&<p role="status">{message}</p>}
 {adding&&<fieldset disabled={busy} className="border rounded-xl p-4 my-4"><legend>Add from approved administrators</legend><label className="block">Search<input className="border rounded p-2 block" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="block my-3">Approved person<select className="border rounded p-2 block" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a person</option>{available.map(p=><option key={p.id} value={p.id}>{p.name} — {p.email}</option>)}</select></label><label>Access level<select className="border rounded p-2 mx-2" value={level} onChange={e=>setLevel(e.target.value)}><option value="view">View only</option><option value="edit">View and edit</option></select></label><button className="pay-gold" disabled={!available.some(p=>p.id===selected)} onClick={()=>change(available.find(p=>p.id===selected),level)}>Add to payroll access</button><button className="pay-outline ml-2" onClick={()=>setAdding(false)}>Cancel</button>{!available.length&&<p>No matching approved administrators to add.</p>}</fieldset>}
 {editing&&<fieldset disabled={busy} className="border rounded-xl p-4 my-4"><legend>Edit approved user</legend><p className="text-sm">Name and email are shared with the main user account.</p><label className="block">Name<input className="border rounded p-2 block" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="block">Email<input type="email" className="border rounded p-2 block" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><button className="pay-gold mt-3" disabled={!editing.name.trim()||!editing.email.trim()} onClick={saveDetails}>Save person</button><button className="pay-outline ml-2" onClick={()=>setEditing(null)}>Cancel</button></fieldset>}
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Name','Email','Payroll access','Account','Actions'].map(x=><th key={x} className="text-left p-3">{x}</th>)}</tr></thead><tbody>{members.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.name||'—'}</td><td>{p.email}</td><td>{p.owner?'Owner — full access':<select aria-label={`Payroll access for ${p.email}`} disabled={busy} value={p.level} onChange={e=>change(p,e.target.value)} className="border rounded p-2"><option value="view">View only</option><option value="edit">View and edit</option></select>}</td><td>{p.status}{p.last_invite_sent&&<small className="block">Invited {new Date(p.last_invite_sent).toLocaleDateString('en-AU')}</small>}</td><td>{p.owner?'Owner access retained':<div className="flex gap-2 flex-wrap"><button className="pay-outline" disabled={busy} onClick={()=>setEditing({...p})}>Edit person</button><button className="pay-outline" disabled={busy} onClick={()=>change(p,'none')}>Remove</button>{['invited','pending_invite','invited_pending_send'].includes(p.status)&&<button className="pay-outline" disabled={busy} onClick={()=>invite(p)}>Send invitation</button>}</div>}</td></tr>)}</tbody></table></div></section>;
}
