import React,{useEffect,useState} from 'react';
import api,{apiError} from '../../lib/api';
const kinds=[['pay-categories','Pay categories'],['deduction-categories','Deduction categories'],['chart-of-accounts','Chart of accounts']];
export default function PayrollCatalogSettings(){
 const [kind,setKind]=useState('pay-categories'),[data,setData]=useState(null),[headers,setHeaders]=useState({}),[table,setTable]=useState('Export'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[query,setQuery]=useState('');
 const url=`/payroll/employee-records/configuration/catalog/${kind}`;
 useEffect(()=>{let active=true;setData(null);setMessage('');api.get(url).then(({data:d})=>{if(active){setHeaders(d.headers);setData({revision:d.revision,tables:d.tables,source:d.source});setTable(Object.keys(d.headers)[0]);setDirty(false);}}).catch(e=>{if(active)setMessage(apiError(e));});return()=>{active=false;};},[url]);
 async function upload(file){if(!file)return;setBusy(true);setMessage('');try{const body=new FormData();body.append('file',file);const {data:d}=await api.post(url+'/preview',body);setData({...data,...d});setTable(Object.keys(d.tables)[0]);setDirty(true);setMessage('Extract loaded for review. Select Save definitions to keep it.');}catch(e){setMessage(apiError(e)||'Could not read extract');}finally{setBusy(false);}}
 async function save(){setBusy(true);try{const {data:d}=await api.put(url,data);setData(d);setDirty(false);setMessage('Definitions saved. No pay runs or external accounts were changed.');}catch(e){setMessage(apiError(e));}finally{setBusy(false);}}
 function patch(index,key,value){setData({...data,tables:{...data.tables,[table]:data.tables[table].map((r,i)=>i===index?{...r,[key]:value}:r)}});setDirty(true);}
 const rows=data?.tables[table]||[],columns=rows.length?Object.keys(rows[0]):headers[table]||[];
 return <section className="pay-panel" id="pay-category-definitions"><h3>Payroll category and accounting definitions</h3><p className="text-sm my-3">Keep the source categories, tax and super classifications, and account mappings here. These are migration definitions: saving them does not activate new calculation rules, transmit STP or post to Xero. Employee core rates are applied separately in Employee settings.</p><div className="flex flex-wrap gap-3 my-3">{kinds.map(([k,label])=><button type="button" key={k} className={kind===k?'pay-gold':'pay-outline'} disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved definition changes?')){setKind(k);setQuery('');}}}>{label}</button>)}</div>{message&&<p role="status" className="pay-notice">{typeof message==='string'?message:JSON.stringify(message)}</p>}{data&&<fieldset disabled={busy}><div className="flex flex-wrap gap-3 items-end"><label>Import extract (.xlsx)<input type="file" accept=".xlsx" onChange={e=>upload(e.target.files[0])} className="block"/></label><label>Table<select className="border rounded p-2 block" value={table} onChange={e=>{setTable(e.target.value);setQuery('');}}>{Object.keys(headers).map(t=><option key={t}>{t}</option>)}</select></label><label>Search<input className="border rounded p-2 block" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="text-sm my-3">{rows.length} definitions · {data.source||'Entered manually'}</p><div className="overflow-auto max-h-96"><table className="text-xs"><thead><tr>{columns.map(c=><th key={c} className="text-left p-2 min-w-36">{c}</th>)}<th>Remove</th></tr></thead><tbody>{rows.map((r,i)=>({r,i})).filter(({r})=>Object.values(r).some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))).map(({r,i})=><tr key={i}>{columns.map(c=><td key={c} className="p-1"><input aria-label={`${c} row ${i+1}`} className="border rounded p-2 w-full min-w-36" value={r[c]??''} onChange={e=>patch(i,c,typeof r[c]==='number'&&e.target.value!==''?Number(e.target.value):e.target.value)}/></td>)}<td><button type="button" className="underline p-2" onClick={()=>{setData({...data,tables:{...data.tables,[table]:rows.filter((_,j)=>j!==i)}});setDirty(true);}}>Remove</button></td></tr>)}</tbody></table></div><div className="pay-actions"><button type="button" className="pay-outline" onClick={()=>{setData({...data,tables:{...data.tables,[table]:[...rows,Object.fromEntries(columns.map(c=>[c,'']))]}});setDirty(true);}}>Add definition</button><button type="button" className="pay-gold" disabled={!dirty} onClick={save}>Save definitions</button></div></fieldset>}</section>;
}
