import React,{useState} from 'react';
import api,{apiError} from '../../lib/api';
import {payBtn,payBtnStyle} from './PayShell';
export default function PayrollConnections(){
  const [form,setForm]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){setBusy(true);try{const {data}=await api.get('/payroll/workbench/connections/settings');setForm({super_provider:data.super_provider||'',stp_provider:data.stp_provider||'',notes:data.notes||''});setMessage('');}catch(e){setMessage(apiError(e)||'Could not load setup');}finally{setBusy(false);}}
  async function save(){setBusy(true);try{await api.put('/payroll/workbench/connections/settings',form);setMessage('Setup notes saved. Both connections remain not connected.');}catch(e){setMessage(apiError(e)||'Could not save setup');}finally{setBusy(false);}}
  return <details className="border rounded-xl p-4"><summary className="font-bold cursor-pointer">Super and ATO reporting connections Â· Not connected</summary><div className="grid sm:grid-cols-2 gap-3 my-3"><div className="bg-slate-50 p-3 rounded-lg"><h4 className="font-semibold">Super contributions</h4><p className="text-sm">Contribution calculation and CSV reporting are available; SuperStream submission, payment and receipt tracking are not connected.</p><p className="text-sm mt-2"><strong>CareSuper / QuickSuper</strong> — CareSuper offers Westpac’s QuickSuper clearing house for contribution file uploads. CareSuper fund ABN: 74 559 365 913 · USI: MTA0100AU. Each employee keeps their own chosen fund.</p><p className="text-sm mt-2">The contribution file format must be matched and tested before uploads are enabled.</p><a className="text-sm underline" href="https://www.caresuper.com.au/employers/super-payments/how-to-make-super-payments" target="_blank" rel="noopener noreferrer">CareSuper employer payments and login</a></div><div className="bg-slate-50 p-3 rounded-lg"><h4 className="font-semibold">ATO Â· Single Touch Payroll</h4><p className="text-sm">Sending-service connection, product registration and testing are still required. PAYG reports are for reconciliation; they are not STP lodgements or BAS submissions.</p></div></div><button type="button" disabled={busy} onClick={load} className={payBtn('ghost')} style={payBtnStyle('ghost')}>Edit provider setup notes</button>{form&&<div className="space-y-3 mt-3"><button type="button" disabled={busy} onClick={()=>setForm({...form,super_provider:"CareSuper / QuickSuper"})} className={payBtn('ghost')} style={payBtnStyle('ghost')}>Use CareSuper / QuickSuper in setup notes</button>{[['super_provider','Super provider / clearing house (when known)'],['stp_provider','STP sending-service provider (when selected)'],['notes','Setup notes â€” do not enter passwords, TFNs or API keys']].map(([k,l])=><label className="block text-sm" key={k}>{l}<input className="w-full border rounded p-2" maxLength={k==='notes'?1000:160} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button type="button" disabled={busy} onClick={save} className={payBtn('ghost')} style={payBtnStyle('ghost')}>Save setup notes</button></div>}{message&&<p role="status" className="text-sm mt-2">{typeof message==='string'?message:JSON.stringify(message)}</p>}</details>;
}
