import React from 'react';
import {render,screen,fireEvent} from '@testing-library/react';
import PayRunEmployee from './PayRunEmployee';
import {money,payRunSummary,sortPayRunEmployees,editPayRunEntry} from './payRunAdapter';
jest.mock('react-router-dom',()=>({Link:({children,to})=><a href={to}>{children}</a>}));
jest.mock('../../lib/api',()=>({__esModule:true,default:{get:jest.fn(()=>new Promise(()=>{}))}}));
const row={worker_id:'a',entry:{ordinary:38,annual:2,hours_reviewed:true,super_reviewed:true,allowance_units:{travel:3}},profile:{hourly_rate:40,allowance_rates:[{code:'travel',name:'Travel',rate:10}],leave_loading_percent:0}};
const result={ordinary_pay:100,ot1_pay:20,ot2_pay:30,night_pay:40,holiday_work_pay:50,annual_pay:60,personal_pay:70,public_holiday_pay:80,leave_loading:10,taxable_allowances:11,meal_allowance_pay:12,configured_allowances:13,gross:596,payg:100,net:496,super:30,reimbursements:0,annual_base_value:null,review_ready:true};
function props(overrides={}){return {companyLabel:'Paneltec',periodEnding:'13/10/2026',employees:[{id:'a',name:'Aaron'},{id:'b',name:'Beth'}],row,calculation:result,sheet:{rules:{ot1_multiplier:1.5,ot2_multiplier:2,night_multiplier:2,holiday_work_multiplier:2.5,super_percent:12},payday:'2026-10-15'},week:'2026-10-07',checkedCount:0,onPatch:jest.fn(),onSaveDraft:jest.fn(),onMarkChecked:jest.fn(),onSelect:jest.fn(),preparationUrl:'/prepare',...overrides};}
test('server totals include allowances and preserve unknown balances',()=>{const p=payRunSummary(row,result);expect(p.allowances).toBe(36);expect(p.overtime).toBe(140);expect(p.leaveAndLoading).toBe(220);expect(p.gross).toBe(596);expect(p.annualLeaveBalance).toBeNull();expect(money(null)).toBe('—');expect(payRunSummary(row,null).gross).toBeUndefined();});
test('sort names without changing source',()=>{const list=[{name:'Zoe'},{name:'Aaron'}];expect(sortPayRunEmployees(list)[0].name).toBe('Aaron');expect(list[0].name).toBe('Zoe');});
test('save and mark use server callbacks without advancing prematurely',()=>{const p=props();render(<PayRunEmployee {...p}/>);fireEvent.click(screen.getByText('Save draft'));expect(p.onSaveDraft).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByText('Mark checked & next'));expect(p.onMarkChecked).toHaveBeenCalledTimes(1);expect(p.onSelect).not.toHaveBeenCalled();});
test('server guard prevents marking despite available PAYG',()=>{render(<PayRunEmployee {...props({calculation:{...result,review_ready:false}})}/>);expect(screen.getByText('Mark checked & next').disabled).toBe(true);});
test('locked and unsupported fields cannot be edited',()=>{render(<PayRunEmployee {...props({locked:true})}/>);expect(screen.getByLabelText('Ordinary hours').disabled).toBe(true);expect(screen.getByLabelText('Saturday OT').disabled).toBe(true);expect(screen.getByLabelText('Living away from home allowance (LAFHA)').value).toBe('');expect(screen.getByText('Save draft').disabled).toBe(true);});
test('other earnings edits and removal update stored allowances',()=>{const p=props();render(<PayRunEmployee {...p}/>);fireEvent.change(screen.getByLabelText('Units'),{target:{value:'4'}});expect(p.onPatch).toHaveBeenLastCalledWith('allowance_units',{travel:4});fireEvent.click(screen.getByLabelText('Remove this earning'));expect(p.onPatch).toHaveBeenLastCalledWith('allowance_units',{});});

test('add earning works without linked rates and exposes setup links',()=>{render(<PayRunEmployee {...props({row:{...row,entry:{...row.entry,allowance_units:{}},profile:{...row.profile,allowance_rates:[]}}})}/>);const add=screen.getByText('Add another earning');expect(add.disabled).toBe(false);fireEvent.click(add);expect(screen.getByLabelText('Earning category')).toBeTruthy();expect(screen.getByText('Browse pay categories').getAttribute('href')).toBe('/app/pay/settings#pay-category-definitions');expect(screen.getByText('Set employee earning rates').getAttribute('href')).toBe('/app/pay/employees?worker=a');expect(screen.getByLabelText('Units').disabled).toBe(true);});

test('search keeps matching people visible until a person is selected',()=>{const p=props({employees:[{id:'a',name:'Aaron'},{id:'b',name:'Adam'},{id:'c',name:'Beth'}]});render(<PayRunEmployee {...p}/>);fireEvent.change(screen.getByLabelText('Search employee'),{target:{value:'a'}});expect(p.onSelect).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Aaron'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Adam'}));expect(p.onSelect).toHaveBeenCalledWith('b');});
test('annual leave taken shows its pay including leave loading',()=>{expect(payRunSummary(row,result).annualLeaveTakenPay).toBe(70);render(<PayRunEmployee {...props()}/>);expect(screen.getByText('Taken this pay').parentElement.textContent).toContain('$70.00');});

test('imported hours editable, source shifts preserved',()=>{const p=props({row:{...row,shifts:[{start:'07:00',finish:'15:00'}]}});render(<PayRunEmployee {...p}/>);expect(screen.getByLabelText('Ordinary hours').disabled).toBe(false);fireEvent.change(screen.getByLabelText('Ordinary hours'),{target:{value:'30'}});expect(p.onPatch).toHaveBeenCalledWith('ordinary',30);const edited=editPayRunEntry(p.row,'ordinary',30,{ordinary:38,ot1:4,ot2:2});expect(edited.shifts).toBe(p.row.shifts);expect(edited.worked_hours_override).toBe(true);expect(edited.entry.ot1).toBe(4);expect(edited.entry.ordinary).toBe(30);expect(edited.entry.super_reviewed).toBe(false);});
test('combined check and edits clear review',()=>{const checked=editPayRunEntry(row,'hours_reviewed',true);expect(checked.entry.super_reviewed).toBe(true);const edited=editPayRunEntry(checked,'annual',3);expect(edited.entry.hours_reviewed).toBe(false);expect(edited.entry.super_reviewed).toBe(false);});
test('clear super override resumes automatic mode',()=>{const p=props({row:{...row,entry:{...row.entry,qualifying_earnings:1000}}});render(<PayRunEmployee {...p}/>);fireEvent.click(screen.getByText('Use automatic'));expect(p.onPatch).toHaveBeenCalledWith('qualifying_earnings',null);});

test('day selector edits a dated bucket and leaves payslip as weekly total',()=>{const onDayPatch=jest.fn();render(<PayRunEmployee {...props({onDayPatch,dailyTotals:{'2026-10-07':{ordinary:6},'2026-10-08':{ordinary:8}}})}/>);fireEvent.change(screen.getByLabelText('Review pay day'),{target:{value:'2026-10-08'}});expect(screen.getByLabelText('Ordinary hours').value).toBe('8');fireEvent.change(screen.getByLabelText('Ordinary hours'),{target:{value:'7'}});expect(onDayPatch).toHaveBeenCalledWith('2026-10-08','ordinary',7);expect(screen.getByText('Day hours · payslip shows weekly total')).toBeTruthy();fireEvent.change(screen.getByLabelText('Review pay day'),{target:{value:''}});expect(screen.getByLabelText('Ordinary hours').value).toBe('38');});
test('configured earning is selectable and sends its rule snapshot',()=>{const rule={code:'site',name:'Site',basis:'fixed_rate',rate:10,multiplier:1,taxable:true,superable:true};const onEarnings=jest.fn();const p=props({onEarnings,sheet:{...props().sheet,rules:{...props().sheet.rules,earning_rules:[rule]}},row:{...row,entry:{...row.entry,allowance_units:{}}}});render(<PayRunEmployee {...p}/>);fireEvent.click(screen.getByText('Add another earning'));fireEvent.change(screen.getByLabelText('Earning category'),{target:{value:'rule:site'}});expect(onEarnings).toHaveBeenLastCalledWith({allowance_units:{},earning_units:{site:0}},[rule]);expect(screen.getByLabelText('Units').disabled).toBe(false);});
test('weekly editing of daily totals activates override without deleting days',()=>{const original={...row,shifts:null,daily_hours:{'2026-10-07':{ordinary:8}}};const edited=editPayRunEntry(original,'ordinary',10,{ordinary:8});expect(edited.worked_hours_override).toBe(true);expect(edited.daily_hours).toBe(original.daily_hours);});
