import * as Dialog from '@radix-ui/react-dialog';
import {FlowSteps,FlowHeading,PayMetrics,PayBadge,cash} from './PayrollFlow';
import PayrollCompletion from './PayrollCompletion';
import PayrollTimesheetDays from './PayrollTimesheetDays';
import DateField from './DateField';
import {useSearchParams,Link} from 'react-router-dom';
import React, { useEffect, useState } from 'react';
import api, { apiError } from '../../lib/api';
import { PayCard, payBtn, payBtnStyle } from './PayShell';
import PayrollBankPanel from './PayrollBankPanel';
import PayrollLeavePanel from './PayrollLeavePanel';
import PayrollConnections from './PayrollConnections';
import PayrollReports from './PayrollReports';
import PayrollHistory from './PayrollHistory';
import PayrollArchive from './PayrollArchive';
import PayrollLifecycle from './PayrollLifecycle';
import PayrollIssuing from './PayrollIssuing';
import PayrollEmployeeRecord from './PayrollEmployeeRecord';

const money = n => n == null ? 'Needs review' : new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(n);
const hours = n => n == null ? 'Not entered' : `${Number(n).toFixed(2)} h`;
function currentFriday() { const d = new Date(); d.setDate(d.getDate() - (d.getDay() + 2) % 7); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
const profile = { employment_type:'unconfirmed', hourly_rate:0, ordinary_weekly_hours:38, classification:'', conditions_reviewed:false, tax_mode:'unconfirmed', tax_declaration_reviewed:false, annual_weeks:4, personal_weeks:2, leave_loading_percent:0 };
const entry = { ordinary:0, ot1:0, ot2:0, annual:0, personal:0, public_holiday:0, taxable_allowances:0, post_tax_deductions:0, reimbursements:0, extra_withholding:0, manual_payg:null, payg_reference:'', qualifying_earnings:null, super_reviewed:false, hours_reviewed:false, opening_annual:null, opening_personal:null };
const inputClass = 'w-full border rounded-lg px-3 py-2 bg-white text-slate-900';
function NumberField({ label, value, onChange, nullable=false, min=0 }) { return <label className="text-sm block">{label}<input className={inputClass} type="number" min={min} step="any" value={value ?? ''} onChange={e => onChange(e.target.value === '' && nullable ? null : Number(e.target.value))} /></label>; }
function Check({children, checked, onChange}) { return <label className="flex gap-2 text-sm items-start py-2"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="mt-1"/>{children}</label>; }

export default function PayWorkbench() {
  const [searchParams]=useSearchParams();
  const [step,setStep]=useState(2),[editorOpen,setEditorOpen]=useState(false),[branding,setBranding]=useState(null);
  useEffect(()=>{api.get('/payroll/workbench/branding').then(r=>setBranding(r.data.settings)).catch(()=>{});},[]);
  const [submitted,setSubmitted]=useState({});
  const [locked,setLocked]=useState(false),[sealedBranding,setSealedBranding]=useState(null);
  const [week,setWeek] = useState(currentFriday), [loadedWeek,setLoadedWeek] = useState('');
  const [sheet,setSheet] = useState(null), [workers,setWorkers] = useState([]), [report,setReport] = useState(null);
  const [selected,setSelected] = useState(''), [query,setQuery] = useState(''), [busy,setBusy] = useState(false);
  const [dirty,setDirty] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState(''), [sources,setSources] = useState([]);
  async function load(target) {
    setBusy(true); setError('');
    try { const [loaded,feed]=await Promise.all([api.get(`/payroll/workbench/${target}`),api.get(`/payroll/workbench/${target}/submissions`)]);const data=loaded.data; const incoming={...data.worksheet};if(!data.saved_at&&searchParams.get('payday'))incoming.payday=searchParams.get('payday');setSheet(incoming);setLocked(data.state==='finalized');setStep(data.state==='finalized'?6:2); setSealedBranding(data.finalized_branding||null); setWorkers(data.workers); setReport(data.report); setSources(data.sources); setSubmitted(feed.data.workers); setLoadedWeek(target); setSelected(data.worksheet.rows[0]?.worker_id || ''); setDirty(false); setMessage(data.saved_at ? `Saved ${new Date(data.saved_at).toLocaleString('en-AU')}` : 'Current Simpro employees loaded. Submitted hours are estimates for review; no missing days or balances are assumed.'); }
    catch(e) { setError(apiError(e) || 'Could not load payroll worksheet'); } finally { setBusy(false); }
  }
  useEffect(()=>{const target=searchParams.get('week');if(target){setWeek(target);load(target);}},[searchParams]);
  useEffect(()=>{ const f=e=>{if(dirty){e.preventDefault();e.returnValue='';}}; window.addEventListener('beforeunload',f); return()=>window.removeEventListener('beforeunload',f); },[dirty]);
  function change(next) { setSheet({...next, reviewed:false}); setDirty(true); setReport(null); setMessage('Unsaved changes — calculate and save to refresh reports.'); }
  function patchRow(section,key,value) { change({...sheet, rows:sheet.rows.map(r=>r.worker_id===selected ? {...r,[section]:{...r[section],[key]:value}} : r)}); }
  async function calculate(save=false, reviewed=false) {
    setBusy(true); setError('');
    try { const body={...sheet, reviewed}; const {data}=save ? await api.put(`/payroll/workbench/${loadedWeek}`,body) : await api.post(`/payroll/workbench/${loadedWeek}/preview`,body);
      setReport(save ? data.report : data); if(save){setSheet({...body,revision:data.revision});setDirty(false);} setMessage(save ? `${reviewed ? 'Reviewed' : 'Draft'} worksheet saved. No payments, STP or leave-ledger changes made.` : 'Calculated preview. Save before downloading reports.');return true;
    } catch(e){setError(apiError(e)||'Calculation failed');return false;}finally{setBusy(false);}
  }
  async function download(kind) {
    setBusy(true);setError('');
    try {const {data}=await api.get(`/payroll/workbench/${loadedWeek}/report/${kind}`,{responseType:'blob'});const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=`paneltec-${kind}-${loadedWeek}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError('Could not download the saved report.');}finally{setBusy(false);}
  }
  async function refreshHours(){
    if(!window.confirm('Replace this employee worked/public-holiday hours with the latest submissions? Other adjustments and leave stay unchanged.'))return;
    setBusy(true);try{const {data}=await api.get(`/payroll/workbench/${loadedWeek}/submissions`);setSubmitted(data.workers);const source=data.workers[selected];change({...sheet,rows:sheet.rows.map(r=>r.worker_id===selected?{...r,timesheet_fingerprint:source?.fingerprint||'',entry:{...r.entry,ordinary:0,ot1:0,ot2:0,public_holiday:0,...source?.totals,hours_reviewed:false,super_reviewed:false}}:r)});}catch(e){setError(apiError(e)||'Could not refresh submitted hours');}finally{setBusy(false);}
  }
  const row=sheet?.rows.find(r=>r.worker_id===selected), result=report?.rows.find(r=>r.worker_id===selected)?.result;
  const btn=(label,fn,disabled=false,gold=false)=><button type="button" disabled={busy||disabled} onClick={fn} className={payBtn(gold?'gold':'ghost')} style={payBtnStyle(gold?'gold':'ghost')}>{label}</button>;
  if(!searchParams.get('week')&&!loadedWeek)return <PayCard title="Choose a pay run"><Link className="text-indigo-700 underline" to="/app/pay">Start a new pay run or open a saved run</Link></PayCard>;
  const edit=id=>{setSelected(id);setEditorOpen(true);};
  const worker=id=>workers.find(w=>w.id===id)||{name:report?.rows.find(r=>r.worker_id===id)?.name||id};
  const totalHours=r=>['ordinary','ot1','ot2','annual','personal','public_holiday'].reduce((a,k)=>a+Number(r.entry[k]||0),0);
  const sourceStatus=id=>{const days=submitted[id]?.days||[];return !days.length?['Not submitted','warn']:days.some(d=>d.status==='submitted')?['Sent · waiting','info']:days.every(d=>d.status==='approved')?['Approved','good']:['Check days','warn'];};
  const filtered=sheet?.rows.filter(r=>worker(r.worker_id).name.toLowerCase().includes(query.toLowerCase()))||[];
  const titles={2:'Gather hours, leave and extras',3:'Calculate pay',4:'Review pay run',5:'Approve and lock',6:'Pay and report',7:'Close pay run'};
  const selectedReport=report?.rows.find(r=>r.worker_id===selected);
  return <div className="pay-theme">
    <FlowHeading step={step} title={titles[step]} week={loadedWeek} payday={sheet?.payday}><FlowSteps step={step} locked={locked} onChange={n=>n===1?window.location.assign('/app/pay'):setStep(n)}/></FlowHeading>
    {error&&<p role="alert" className="pay-notice">{typeof error==='string'?error:JSON.stringify(error)}</p>}
    {message&&<p role="status" className="text-sm mb-4 text-slate-600">{message}</p>}
    {!sheet?<div className="pay-panel">{busy?'Loading this pay run…':'Could not load this pay run.'}</div>:<>
    {step===2&&<>
      <PayMetrics items={[["Timesheets approved",sheet.rows.filter(r=>sourceStatus(r.worker_id)[1]==='good').length+` of ${sheet.rows.length}`],["Leave in run",sheet.rows.reduce((a,r)=>a+r.entry.annual+r.entry.personal,0).toFixed(1)+' h'],["Allowances",cash(sheet.rows.reduce((a,r)=>a+r.entry.taxable_allowances,0))],["Hours in run",sheet.rows.reduce((a,r)=>a+totalHours(r),0).toFixed(1)]]}/>
      <section className="pay-panel"><div className="flex justify-between gap-3 mb-4 flex-wrap"><h3>Employees and submitted time</h3><input aria-label="Find worker in worksheet" placeholder="Find employee…" className="border rounded-lg p-2" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="overflow-x-auto"><table className="pay-table"><thead><tr><th>Person</th><th>Ordinary</th><th>Overtime</th><th>Leave</th><th>Allowances</th><th>Timesheet</th><th/></tr></thead><tbody>{filtered.map(r=>{const [label,tone]=sourceStatus(r.worker_id);return <tr className={tone==='warn'?'attention':''} key={r.worker_id}><td><button className="name" onClick={()=>edit(r.worker_id)}>{worker(r.worker_id).name}</button><small>{worker(r.worker_id).department||r.profile.classification}</small></td><td>{r.entry.ordinary.toFixed(1)}</td><td>{(r.entry.ot1+r.entry.ot2).toFixed(1)}</td><td>{(r.entry.annual+r.entry.personal).toFixed(1)}</td><td>{cash(r.entry.taxable_allowances)}</td><td><PayBadge tone={tone}>{label}</PayBadge></td><td><button className="pay-outline" onClick={()=>edit(r.worker_id)}>Check / edit</button></td></tr>})}</tbody></table></div><label className="text-sm block mt-5">Include an omitted Simpro employee <select disabled={locked} className="border rounded p-2 ml-2" value="" onChange={e=>{const id=e.target.value;if(!id)return;const source=submitted[id];change({...sheet,rows:[...sheet.rows,{worker_id:id,profile:{...profile},entry:{...entry,...source?.totals},timesheet_fingerprint:source?.fingerprint||''}]});edit(id);}}><option value="">Select employee</option>{workers.filter(w=>!sheet.rows.some(r=>r.worker_id===w.id)).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></section>
      <div className="pay-notice">Review missing time and approved leave for every included employee. No pay is assumed for missing days; incomplete records prevent the run being marked reviewed.</div><div className="pay-actions">{btn('Save draft',()=>calculate(true),locked)}<button className="pay-gold" onClick={()=>setStep(3)}>Continue to calculation</button></div>
    </>}
    {step===3&&<section className="pay-panel"><h3>Payment date and reviewed calculation rules</h3><fieldset disabled={busy||locked}><div className="grid sm:grid-cols-4 gap-4"><label className="text-sm">Actual wage payment date<DateField className={inputClass} value={sheet.payday} onChange={e=>change({...sheet,payday:e.target.value})}/></label>{[['ot1_multiplier','Overtime tier 1 multiplier'],['ot2_multiplier','Overtime tier 2 multiplier'],['super_percent','Super contribution %']].map(([key,label])=><NumberField key={key} label={label} min={key==='super_percent'?12:1} value={sheet.rules[key]} onChange={v=>change({...sheet,rules:{...sheet.rules,[key]:v}})}/>)}</div></fieldset><div className="pay-notice">Overtime multipliers are reviewed settings, not automatic award interpretation. Super uses reviewed qualifying earnings. Confirm the payment date and each employee’s tax, hours and employment conditions.</div><div className="pay-actions"><button className="pay-outline" onClick={()=>setStep(2)}>Back to inputs</button><button className="pay-gold" disabled={busy} onClick={async()=>{if(locked||await calculate())setStep(4);}}>Calculate and review</button></div></section>}
    {step===4&&<>
      <PayMetrics items={[["Gross pay",cash(report?.totals.gross)],["Tax withheld (PAYG)",cash(report?.totals.payg)],["Super",cash(report?.totals.super),'Reviewed qualifying earnings'],["Net to bank",cash(report?.totals.net),`${sheet.rows.length} employees`,true]]}/>
      {!report&&<div className="pay-notice">Changes need recalculating. <button className="pay-outline" onClick={()=>calculate()}>Calculate now</button></div>}
      <div className="pay-grid"><section className="pay-panel"><div className="overflow-auto"><table className="pay-table"><thead><tr><th>Person</th><th>Hours</th><th>Gross</th><th>Tax</th><th>Super</th><th>Net</th><th>Check</th></tr></thead><tbody>{(report?.rows||[]).map(r=><tr key={r.worker_id} className={selected===r.worker_id?'selected':''}><td><button className="name" onClick={()=>edit(r.worker_id)}>{r.name}</button><button className="block text-xs mt-1 underline" onClick={()=>setSelected(r.worker_id)}>Preview payslip</button></td><td>{totalHours(r).toFixed(1)}</td>{['gross','payg','super','net'].map(k=><td key={k} className="num">{cash(r.result[k])}</td>)}<td><PayBadge tone={r.result.review_ready?'good':'warn'}>{r.result.review_ready?'Checked':`${r.result.issues.length} checks`}</PayBadge></td></tr>)}</tbody></table></div></section><aside className="space-y-4"><section className="pay-panel"><h3>Payslip preview</h3>{selectedReport?<><strong>{selectedReport.name}</strong><dl className="grid grid-cols-2 gap-3 text-sm mt-4">{[['Gross',selectedReport.result.gross],['PAYG',selectedReport.result.payg],['Net pay',selectedReport.result.net],['Super',selectedReport.result.super]].map(([l,v])=><React.Fragment key={l}><dt>{l}</dt><dd className="text-right font-bold">{cash(v)}</dd></React.Fragment>)}</dl><button className="pay-outline mt-4" onClick={()=>edit(selectedReport.worker_id)}>Edit this employee</button></>:<p>Calculate pay to preview.</p>}</section><div className="pay-notice"><strong>Review every employee</strong><p>{report?.rows.reduce((a,r)=>a+r.result.issues.length,0)||0} recorded checks remain. Compare hours and amounts with approved records; automatic prior-week variance checks are not yet available.</p></div></aside></div>
      <details className="pay-panel mt-5"><summary className="font-bold cursor-pointer">Reports and full payslip preview</summary><PayrollReports sealedBranding={sealedBranding} report={report} sheet={sheet} week={loadedWeek} dirty={dirty} busy={busy} onCalculate={()=>calculate()} onDownload={download} sealedBranding={sealedBranding}/></details>
      <div className="pay-actions"><button className="pay-outline" onClick={()=>setStep(2)}>Back to inputs</button>{btn('Save draft',()=>calculate(true),locked)}<button className="pay-gold" disabled={busy||(!locked&&!report?.ready)} onClick={async()=>{if(locked||await calculate(true,true))setStep(5);}}>Continue to approval</button></div>
    </>}
    <div hidden={step!==5}><PayrollLifecycle week={loadedWeek||week} revision={sheet?.revision||0} dirty={dirty} onReload={load} onLocked={setLocked}/><div className="pay-notice">Only authorised payroll employees can approve. This version records the approver but does not enforce a different preparer and approver.</div><div className="pay-actions"><button className="pay-outline" onClick={()=>setStep(4)}>Back to review</button><button className="pay-gold" disabled={!locked} onClick={()=>setStep(6)}>Continue to pay and report</button></div></div>
    {(step===6||step===7)&&<PayrollCompletion week={loadedWeek} sheet={sheet} report={report} workers={workers} dirty={dirty} locked={locked} step={step} onStep={setStep} onDownload={download}/>}
    <Dialog.Root open={editorOpen} onOpenChange={setEditorOpen}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 bg-indigo-950/50 z-[80]"/><Dialog.Content className="pay-theme pay-drawer fixed right-0 top-0 z-[81]" aria-describedby="pay-edit-description"><div className="pay-drawer-header"><div><p className="pay-eyebrow">Edit pay · {worker(selected).department||'Employee'} · {cash(row?.profile.hourly_rate)} / h</p><Dialog.Title asChild><h3>{worker(selected).name}</h3></Dialog.Title><p id="pay-edit-description" className="text-sm">Week {loadedWeek} · {locked?'Finalised figures are locked':'Changes are saved with this pay-run revision'}</p></div><Dialog.Close className="pay-outline" aria-label="Close employee editor">×</Dialog.Close></div>
    {row&&<><fieldset disabled={busy||locked} className="space-y-4">
          <PayrollTimesheetDays key={selected+loadedWeek} source={submitted[selected]} onRefresh={refreshHours} onChanged={async()=>{const {data}=await api.get(`/payroll/workbench/${loadedWeek}/submissions`);setSubmitted(data.workers);change({...sheet,rows:sheet.rows.map(r=>r.worker_id===selected?{...r,entry:{...r.entry,hours_reviewed:false,super_reviewed:false}}:r)});}}/>
          <PayrollEmployeeRecord key={selected} workerId={selected} profile={row.profile} onApply={profile=>change({...sheet,rows:sheet.rows.map(r=>r.worker_id===selected?{...r,profile}:r)})}/>
          <h4 className="font-semibold">Employment and rates</h4><div className="grid sm:grid-cols-3 gap-3">
            <label className="text-sm">Employment<select className={inputClass} value={row.profile.employment_type} onChange={e=>patchRow('profile','employment_type',e.target.value)}>{[['unconfirmed','Choose…'],['full_time','Full time'],['part_time','Part time'],['casual','Casual'],['contractor','Contractor — separate assessment']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
            {[['hourly_rate','Paid hourly rate $'],['ordinary_weekly_hours','Ordinary hours / week'],['annual_weeks','Annual leave weeks / year'],['personal_weeks','Personal leave weeks / year'],['leave_loading_percent','Annual leave loading %']].map(([k,l])=><NumberField key={k} label={l} value={row.profile[k]} onChange={v=>patchRow('profile',k,v)}/>)}</div>
          <p className="text-xs text-slate-600">38 hours gives 152 annual and 76 personal/carer’s leave hours per full year. Part-time accrual is proportional; casuals do not accrue these paid leave balances. Enter the actual hourly rate including any applicable casual loading, and check how overtime multipliers apply.</p>
          <label className="text-sm block">Award / classification / confirmed award-free basis<input className={inputClass} value={row.profile.classification} onChange={e=>patchRow('profile','classification',e.target.value)}/></label>
          <Check checked={row.profile.conditions_reviewed} onChange={v=>patchRow('profile','conditions_reviewed',v)}>I have checked the worker’s rate, overtime, leave loading and applicable employment conditions.</Check>
          <PayrollLeavePanel key={row.worker_id} week={loadedWeek} row={row} onChange={updated=>change({...sheet,rows:sheet.rows.map(r=>r.worker_id===selected?updated:r)})}/>
          <h4 className="font-semibold">This week’s hours and adjustments</h4><div className="grid sm:grid-cols-3 gap-3">{[['ordinary','Ordinary hours'],['ot1','Overtime tier 1 hours'],['ot2','Overtime tier 2 hours'],['annual','Annual leave taken (hours)'],['personal','Personal/carer’s leave (hours)'],['public_holiday','Paid public holiday hours'],['taxable_allowances','Taxable allowances $'],['post_tax_deductions','Authorised post-tax deductions $'],['reimbursements','Expense reimbursements $']].map(([k,l])=><NumberField key={k} label={l} value={row.entry[k]} onChange={v=>patchRow('entry',k,v)}/>)}</div>
          <Check checked={row.entry.hours_reviewed} onChange={v=>patchRow('entry','hours_reviewed',v)}>Hours, leave, allowances and authorised deductions agree with approved records. Worked public holidays and other penalty rates have been separately checked.</Check>
          <h4 className="font-semibold">PAYG withholding</h4><label className="text-sm block">Tax calculation<select className={inputClass} value={row.profile.tax_mode} onChange={e=>patchRow('profile','tax_mode',e.target.value)}><option value="unconfirmed">Choose after reviewing the tax declaration</option><option value="resident_threshold">Australian resident — tax-free threshold claimed</option><option value="resident_no_threshold">Australian resident — no tax-free threshold</option><option value="manual">Reviewed manual withholding (HELP or other circumstances)</option></select></label>
          <p className="text-xs text-slate-600">Automatic tables apply to standard weekly payments with a TFN provided, without HELP/STSL, Medicare adjustments, offsets or withholding variations. Bonuses, termination payments and other tax situations need a separately calculated manual amount.</p>
          <Check checked={row.profile.tax_declaration_reviewed} onChange={v=>patchRow('profile','tax_declaration_reviewed',v)}>Tax declaration checked and the selected standard tax table applies.</Check>
          <div className="grid sm:grid-cols-2 gap-3"><NumberField nullable label="Manual PAYG $ (manual mode only)" value={row.entry.manual_payg} onChange={v=>patchRow('entry','manual_payg',v)}/><NumberField label="Additional withholding $" value={row.entry.extra_withholding} onChange={v=>patchRow('entry','extra_withholding',v)}/></div><label className="text-sm block">Manual calculation reference<input className={inputClass} value={row.entry.payg_reference} onChange={e=>patchRow('entry','payg_reference',e.target.value)}/></label>
          <h4 className="font-semibold">Super fund and deduction particulars</h4>
          <div className="grid sm:grid-cols-2 gap-3">{[['super_fund_name','Selected super fund name'],['super_fund_usi','Super fund USI']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={inputClass} value={row.profile[key]||''} onChange={e=>patchRow('profile',key,e.target.value)}/></label>)}</div>
          <label className="block text-sm">Deduction particulars (each amount, recipient and authorisation reference)<textarea className={inputClass} maxLength={1000} value={row.entry.deduction_details||''} onChange={e=>patchRow('entry','deduction_details',e.target.value)}/></label>
          <label className="block text-sm">Allowance particulars (each description and amount)<textarea className={inputClass} maxLength={1000} value={row.entry.allowance_details||''} onChange={e=>patchRow('entry','allowance_details',e.target.value)}/></label>
          <p className="text-xs">Use the employee’s selected fund. These details do not enrol the employee or send contributions. Do not enter TFNs or bank account numbers in the notes.</p>
          <h4 className="font-semibold">Super and opening leave balances</h4><div className="grid sm:grid-cols-3 gap-3">{[['qualifying_earnings','Super qualifying earnings $'],['opening_annual','Annual leave opening hours'],['opening_personal','Personal leave opening hours']].map(([k,l])=><NumberField nullable key={k} label={l} value={row.entry[k]} onChange={v=>patchRow('entry',k,v)}/>)}</div>
          <Check checked={row.entry.super_reviewed} onChange={v=>patchRow('entry','super_reviewed',v)}>Super eligibility, qualifying earnings and applicable contribution cap checked.</Check>
          <p className="text-xs text-slate-600">Use verified Wojo balances as at this week’s start. Closing balances below are projections, not posted entitlements. Annual leave value is base pay only; loading and termination rules can change the amount payable. Personal leave is shown in hours, not as a termination payout.</p>
          {result&&<div className="rounded-xl bg-slate-50 p-3 text-sm"><div className="grid sm:grid-cols-3 gap-3"><span>Gross <strong>{money(result.gross)}</strong></span><span>Net <strong>{money(result.net)}</strong></span><span>Super <strong>{money(result.super)}</strong></span><span>Annual accrued {hours(result.annual_accrued)}</span><span>Annual closing {hours(result.annual_closing)}</span><span>Personal closing {hours(result.personal_closing)}</span></div>{result.issues.length>0&&<ul className="list-disc pl-5 mt-3 text-amber-900">{result.issues.map(i=><li key={i}>{i}</li>)}</ul>}</div>}
      <label className="block text-sm font-semibold">Reason for changes (saved in revision history)<textarea className={inputClass} maxLength={1000} value={row.adjustment_reason||''} onChange={e=>change({...sheet,rows:sheet.rows.map(r=>r.worker_id===selected?{...r,adjustment_reason:e.target.value}:r)})}/></label>
      </fieldset><div className="pay-drawer-footer pay-actions"><Dialog.Close className="pay-outline">Close editor</Dialog.Close>{!locked&&<><button className="pay-outline" onClick={()=>{change({...sheet,rows:sheet.rows.filter(r=>r.worker_id!==selected)});setEditorOpen(false);}}>Omit from this run</button><button className="pay-gold" disabled={busy||!row.adjustment_reason?.trim()} onClick={async()=>{if(await calculate(true)){setEditorOpen(false);}}}>Save and recalculate</button></>}</div></>}
      </Dialog.Content></Dialog.Portal></Dialog.Root>
    </>}
  </div>;
}
