"""Audit Exports — generate signed evidence packs (JSON / CSV ZIP / PDF) for
Comcare, SafeWork and client audits."""
from __future__ import annotations
import csv
import hashlib
import io
import json
import os
import zipfile
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field

from auth import get_current_user
from db import db
from models import new_id, now_iso

router = APIRouter(prefix="/audit-exports", tags=["audit-exports"])

UPLOAD_DIR = Path(__file__).parent / "uploads" / "exports"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

ENTITY_MAP = {
    "swms": "swms",
    "pre_starts": "pre_starts",
    "site_diary": "site_diary_entries",
    "hazards": "hazards",
    "incidents": "incidents",
    "inspections": "inspections",
    "contractors": "contractors",
}


class ExportIn(BaseModel):
    workspace_id: Optional[str] = None
    date_from: str
    date_to: str
    include: List[Literal["swms", "pre_starts", "site_diary", "hazards", "incidents", "inspections", "contractors"]] = Field(min_length=1)
    format: Literal["pdf", "csv", "json"] = "pdf"
    title: Optional[str] = None


async def _collect(org_id: str, workspace_id: Optional[str], includes: List[str],
                   date_from: str, date_to: str) -> dict:
    bundle: dict = {}
    for key in includes:
        coll = ENTITY_MAP[key]
        q = {"org_id": org_id, "deleted_at": None}
        if workspace_id and key != "contractors":
            q["workspace_id"] = workspace_id
        # Filter by date for date-bearing entities — fall back to created_at
        if key in {"pre_starts", "site_diary"}:
            q["date"] = {"$gte": date_from, "$lte": date_to}
        elif key == "incidents":
            q["occurred_at"] = {"$gte": date_from, "$lte": date_to + "T23:59:59Z"}
        else:
            q["created_at"] = {"$gte": date_from, "$lte": date_to + "T23:59:59Z"}
        docs = await db[coll].find(q, {"_id": 0}).sort("created_at", -1).to_list(500)
        bundle[key] = docs
    return bundle


def _flatten(value):
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return value


def _csv_zip(bundle: dict) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for entity, docs in bundle.items():
            if not docs:
                zf.writestr(f"{entity}.csv", "(no records in range)\n")
                continue
            cols = sorted({k for d in docs for k in d.keys()})
            sio = io.StringIO()
            w = csv.writer(sio)
            w.writerow(cols)
            for d in docs:
                w.writerow([_flatten(d.get(c, "")) for c in cols])
            zf.writestr(f"{entity}.csv", sio.getvalue())
    return buf.getvalue()


def _pdf(bundle: dict, meta: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm,
                            title=meta.get("title") or "Paneltec Civil Audit Pack")
    styles = getSampleStyleSheet()
    brand_blue = colors.HexColor("#2C6BFF")
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], textColor=brand_blue, fontSize=22, spaceAfter=4)
    eyebrow = ParagraphStyle("Eyebrow", parent=styles["Normal"], textColor=brand_blue, fontSize=8, spaceAfter=2)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)

    story = []
    story.append(Paragraph("PANELTEC CIVIL · AUDIT PACK", eyebrow))
    story.append(Paragraph(meta.get("title") or "Compliance Evidence Pack", h1))
    story.append(Spacer(1, 6))
    meta_table = Table([
        ["Period", f"{meta['date_from']} → {meta['date_to']}"],
        ["Scope", meta.get("scope", "Org-wide")],
        ["Generated", meta["generated_at"]],
        ["Generated by", meta["generated_by"]],
        ["Export ID", meta["export_id"]],
        ["SHA-256", meta["sha256"]],
    ], colWidths=[35 * mm, 130 * mm])
    meta_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 12))

    sec_h = ParagraphStyle("Sec", parent=styles["Heading2"], textColor=brand_blue, fontSize=14, spaceBefore=10)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=11)

    for entity, docs in bundle.items():
        story.append(PageBreak())
        story.append(Paragraph(entity.replace("_", " ").title(), sec_h))
        story.append(Paragraph(f"{len(docs)} record(s) in this pack — first 50 shown.", small))
        story.append(Spacer(1, 6))
        if not docs:
            story.append(Paragraph("<i>No records in range.</i>", body))
            continue
        # pick a few sensible columns per entity
        col_map = {
            "swms": ["title", "status", "version", "created_at"],
            "pre_starts": ["date", "crew_lead", "work_summary"],
            "site_diary": ["date", "raw_notes"],
            "hazards": ["title", "severity", "status", "location"],
            "incidents": ["title", "category", "follow_up_status", "occurred_at"],
            "inspections": ["template_name", "date"],
            "contractors": ["name", "trade", "status"],
        }
        cols = col_map.get(entity, list(docs[0].keys())[:4])
        rows = [cols]
        for d in docs[:50]:
            rows.append([str(d.get(c, ""))[:80] for c in cols])
        table = Table(rows, colWidths=[(165 / len(cols)) * mm] * len(cols))
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), brand_blue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(table)

    doc.build(story)
    return buf.getvalue()


@router.post("", status_code=201)
async def create_export(body: ExportIn, user: dict = Depends(get_current_user)):
    bundle = await _collect(user["org_id"], body.workspace_id, body.include, body.date_from, body.date_to)
    counts = {k: len(v) for k, v in bundle.items()}

    export_id = new_id()
    ws_label = "All workspaces"
    if body.workspace_id:
        ws = await db.workspaces.find_one({"id": body.workspace_id})
        ws_label = ws.get("name", "Workspace") if ws else "Workspace"
    meta = {
        "export_id": export_id,
        "title": body.title or "Compliance Evidence Pack",
        "date_from": body.date_from,
        "date_to": body.date_to,
        "scope": ws_label,
        "generated_at": now_iso(),
        "generated_by": user.get("email", ""),
        "counts": counts,
    }

    if body.format == "json":
        payload = json.dumps({"meta": meta, "data": bundle}, ensure_ascii=False, indent=2).encode("utf-8")
        ext = "json"
    elif body.format == "csv":
        payload = _csv_zip(bundle)
        ext = "zip"
    else:
        # PDF needs sha256 in meta; compute a placeholder first
        payload_pre = json.dumps(bundle, ensure_ascii=False, sort_keys=True).encode("utf-8")
        meta["sha256"] = hashlib.sha256(payload_pre).hexdigest()
        payload = _pdf(bundle, meta)
        ext = "pdf"

    sha = hashlib.sha256(payload).hexdigest()
    meta["sha256"] = sha
    filename = f"{export_id}.{ext}"
    path = UPLOAD_DIR / filename
    path.write_bytes(payload)

    record = {
        "id": export_id, "org_id": user["org_id"], "workspace_id": body.workspace_id,
        "title": meta["title"], "date_from": body.date_from, "date_to": body.date_to,
        "include": body.include, "format": body.format,
        "file_url": f"/api/files/exports/{filename}", "filename": filename,
        "sha256": sha, "size_bytes": len(payload), "counts": counts,
        "scope": ws_label, "generated_at": meta["generated_at"],
        "generated_by": user.get("email", ""),
        "created_at": now_iso(),
    }
    await db.audit_exports.insert_one(dict(record))
    record.pop("_id", None)
    return record


@router.get("")
async def list_exports(user: dict = Depends(get_current_user)):
    docs = await db.audit_exports.find({"org_id": user["org_id"]}, {"_id": 0}).sort("created_at", -1).to_list(200)
    return docs


@router.get("/{eid}")
async def get_export(eid: str, user: dict = Depends(get_current_user)):
    doc = await db.audit_exports.find_one({"id": eid, "org_id": user["org_id"]}, {"_id": 0})
    if not doc:
        raise HTTPException(404, "Not found")
    return doc
