"""Audit Exports — generate signed evidence packs (JSON / CSV ZIP / PDF) for
Comcare, SafeWork and client audits."""
from __future__ import annotations
import csv
import hashlib
import io
import json
import os
import zipfile
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field

from auth import get_current_user
from db import db
from models import new_id, now_iso

router = APIRouter(prefix="/audit-exports", tags=["audit-exports"])

UPLOAD_DIR = Path(__file__).parent / "uploads" / "exports"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

ENTITY_MAP = {
    "swms": "swms",
    "pre_starts": "pre_starts",
    "site_diary": "site_diary_entries",
    "hazards": "hazards",
    "incidents": "incidents",
    "inspections": "inspections",
    "contractors": "contractors",
}


class ExportIn(BaseModel):
    workspace_id: Optional[str] = None
    date_from: str
    date_to: str
    include: List[Literal["swms", "pre_starts", "site_diary", "hazards", "incidents", "inspections", "contractors"]] = Field(min_length=1)
    format: Literal["pdf", "csv", "json"] = "pdf"
    title: Optional[str] = None


async def _collect(org_id: str, workspace_id: Optional[str], includes: List[str],
                   date_from: str, date_to: str) -> dict:
    bundle: dict = {}
    for key in includes:
        coll = ENTITY_MAP[key]
        q = {"org_id": org_id, "deleted_at": None}
        if workspace_id and key != "contractors":
            q["workspace_id"] = workspace_id
        # Filter by date for date-bearing entities — fall back to created_at
        if key in {"pre_starts", "site_diary"}:
            q["date"] = {"$gte": date_from, "$lte": date_to}
        elif key == "incidents":
            q["occurred_at"] = {"$gte": date_from, "$lte": date_to + "T23:59:59Z"}
        else:
            q["created_at"] = {"$gte": date_from, "$lte": date_to + "T23:59:59Z"}
        docs = await db[coll].find(q, {"_id": 0}).sort("created_at", -1).to_list(500)
        bundle[key] = docs
    return bundle


def _flatten(value):
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return value


def _csv_zip(bundle: dict) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for entity, docs in bundle.items():
            if not docs:
                zf.writestr(f"{entity}.csv", "(no records in range)\n")
                continue
            cols = sorted({k for d in docs for k in d.keys()})
            sio = io.StringIO()
            w = csv.writer(sio)
            w.writerow(cols)
            for d in docs:
                w.writerow([_flatten(d.get(c, "")) for c in cols])
            zf.writestr(f"{entity}.csv", sio.getvalue())
    return buf.getvalue()


def _pdf(bundle: dict, meta: dict) -> bytes:
    """Phase 3.23 — migrated to the shared `pdf_template`. Audit packs
    now inherit the Paneltec 2-colour brand (orange + slate) so the
    audit team sees a consistent shape across every PDF artefact."""
    import pdf_template as P
    buf = io.BytesIO()
    doc = P.make_doc(buf, 'WHS · Audit pack', meta.get('scope') or 'Org-wide',
                     doc_id=meta.get('export_id'))
    # Synthesise per-entity counts for the evidence sufficiency line.
    total_records = sum(len(v) for v in bundle.values() if isinstance(v, list))
    sufficiency_dict = {
        'attachments': [r for v in bundle.values() if isinstance(v, list)
                        for r in v if isinstance(r, dict) and r.get('photo_url')],
        'controls':    [r for v in bundle.values() if isinstance(v, list)
                        for r in v if isinstance(r, dict) and r.get('controls')],
        'signatures':  [r for v in bundle.values() if isinstance(v, list)
                        for r in v if isinstance(r, dict) and r.get('sign_ons')],
    }
    story: list = []
    story += P.title_block(
        meta.get('title') or 'Compliance Evidence Pack',
        f"{meta['date_from']} → {meta['date_to']}  ·  {meta.get('scope', 'Org-wide')}",
    )
    story.append(P.evidence_sufficiency_line(sufficiency_dict))
    story += P.section_label('Pack manifest')
    story += [P.field_grid([
        ('Title',         meta.get('title')),
        ('Period',        f"{meta['date_from']} → {meta['date_to']}"),
        ('Scope',         meta.get('scope', 'Org-wide')),
        ('Total records', str(total_records)),
        ('Entities',      ', '.join(bundle.keys())),
        ('Generated',     meta.get('generated_at')),
        ('Generated by',  meta.get('generated_by')),
        ('Export ID',     meta.get('export_id')),
        ('SHA-256',       (meta.get('sha256') or '')[:24] + '…' if meta.get('sha256') else None),
    ])]
    # One section per entity in the bundle.
    col_map = {
        'swms':       (['title', 'status', 'version', 'created_at'],
                       ['Title', 'Status', 'Version', 'Created']),
        'pre_starts': (['date', 'crew_lead', 'work_summary'],
                       ['Date', 'Crew lead', 'Work summary']),
        'site_diary': (['date', 'raw_notes'],
                       ['Date', 'Notes']),
        'hazards':    (['title', 'severity', 'status', 'location'],
                       ['Title', 'Severity', 'Status', 'Location']),
        'incidents':  (['title', 'category', 'follow_up_status', 'occurred_at'],
                       ['Title', 'Category', 'Follow-up', 'Occurred']),
        'inspections':(['template_name', 'date', 'status'],
                       ['Template', 'Date', 'Status']),
        'contractors':(['name', 'trade', 'status'],
                       ['Name', 'Trade', 'Status']),
    }
    for entity, docs in bundle.items():
        if not isinstance(docs, list):
            continue
        # Filter out non-dict junk so the renderer can't blow up on
        # legacy/malformed payloads (some old JSON packs stored bare strings).
        docs = [d for d in docs if isinstance(d, dict)]
        story += P.section_label(f"{entity.replace('_', ' ')} · {len(docs)} record{'s' if len(docs) != 1 else ''}")
        if not docs:
            story += [P.Paragraph('No records in this period.', P.BODY_MUTED)]
            continue
        cols_keys, cols_headers = col_map.get(entity,
            (list(docs[0].keys())[:4], [k.replace('_', ' ').title() for k in list(docs[0].keys())[:4]]))
        rows = []
        for d in docs[:50]:
            rows.append([str(d.get(c, '') or '—')[:80] for c in cols_keys])
        story += [P.data_table(cols_headers, rows)]
        if len(docs) > 50:
            story += [P.Paragraph(f"… and {len(docs) - 50} more record{'s' if (len(docs) - 50) != 1 else ''} (truncated for print readability — full data in JSON sibling).", P.BODY_MUTED)]
    # Signed footer block at the very end.
    story += P.section_label('Audit chain')
    story += [P.Paragraph(
        f"<b>Generated by</b> {meta.get('generated_by', '—')}<br/>"
        f"<b>Signed at</b> {meta.get('generated_at', '—')}<br/>"
        f"<b>Pack SHA-256</b> <font face='Courier' size='7'>{meta.get('sha256', '')}</font>",
        P.BODY)]
    story += P.section_label('Signatures')
    story += [P.signatures_section(['Admin', 'HSEQ lead', 'Auditor'])]

    # PDF metadata — auditable provenance baked into the file itself.
    doc.title = meta.get('title') or 'Paneltec Civil Audit Pack'
    doc.author = meta.get('generated_by') or 'Paneltec Civil'
    doc.subject = f"WHS audit pack · {meta['date_from']} → {meta['date_to']}"
    doc.producer = 'Paneltec Civil · paneltec-civil'
    doc.creator = 'Paneltec Civil · audit_exports'

    doc.build(story)
    return buf.getvalue()


@router.post("", status_code=201)
async def create_export(body: ExportIn, user: dict = Depends(get_current_user)):
    bundle = await _collect(user["org_id"], body.workspace_id, body.include, body.date_from, body.date_to)
    counts = {k: len(v) for k, v in bundle.items()}

    export_id = new_id()
    ws_label = "All workspaces"
    if body.workspace_id:
        ws = await db.workspaces.find_one({"id": body.workspace_id})
        ws_label = ws.get("name", "Workspace") if ws else "Workspace"
    meta = {
        "export_id": export_id,
        "title": body.title or "Compliance Evidence Pack",
        "date_from": body.date_from,
        "date_to": body.date_to,
        "scope": ws_label,
        "generated_at": now_iso(),
        "generated_by": user.get("email", ""),
        "counts": counts,
    }

    if body.format == "json":
        payload = json.dumps({"meta": meta, "data": bundle}, ensure_ascii=False, indent=2).encode("utf-8")
        ext = "json"
    elif body.format == "csv":
        payload = _csv_zip(bundle)
        ext = "zip"
    else:
        # PDF needs sha256 in meta; compute a placeholder first
        payload_pre = json.dumps(bundle, ensure_ascii=False, sort_keys=True).encode("utf-8")
        meta["sha256"] = hashlib.sha256(payload_pre).hexdigest()
        payload = _pdf(bundle, meta)
        ext = "pdf"

    sha = hashlib.sha256(payload).hexdigest()
    meta["sha256"] = sha
    filename = f"{export_id}.{ext}"
    path = UPLOAD_DIR / filename
    path.write_bytes(payload)

    record = {
        "id": export_id, "org_id": user["org_id"], "workspace_id": body.workspace_id,
        "title": meta["title"], "date_from": body.date_from, "date_to": body.date_to,
        "include": body.include, "format": body.format,
        "file_url": f"/api/files/exports/{filename}", "filename": filename,
        "sha256": sha, "size_bytes": len(payload), "counts": counts,
        "scope": ws_label, "generated_at": meta["generated_at"],
        "generated_by": user.get("email", ""),
        "created_at": now_iso(),
    }
    await db.audit_exports.insert_one(dict(record))
    record.pop("_id", None)

    # Phase 3.23 — When the user picks JSON or CSV we ALSO write a PDF
    # sibling automatically. Audit packs always need a human-readable
    # artefact alongside the machine-readable one. Failures here never
    # break the primary export: the sibling write is best-effort.
    sibling: dict | None = None
    if body.format != "pdf":
        try:
            pdf_meta = dict(meta)
            pdf_meta["sha256"] = sha   # link PDF to the primary artefact's hash
            pdf_bytes = _pdf(bundle, pdf_meta)
            pdf_sha = hashlib.sha256(pdf_bytes).hexdigest()
            pdf_id = new_id()
            pdf_filename = f"{pdf_id}.pdf"
            (UPLOAD_DIR / pdf_filename).write_bytes(pdf_bytes)
            sibling = {
                "id": pdf_id, "org_id": user["org_id"], "workspace_id": body.workspace_id,
                "title": meta["title"], "date_from": body.date_from, "date_to": body.date_to,
                "include": body.include, "format": "pdf",
                "file_url": f"/api/files/exports/{pdf_filename}", "filename": pdf_filename,
                "sha256": pdf_sha, "size_bytes": len(pdf_bytes), "counts": counts,
                "scope": ws_label, "generated_at": meta["generated_at"],
                "generated_by": user.get("email", ""),
                "created_at": now_iso(),
                "sibling_of": export_id,   # back-reference to the primary artefact
            }
            await db.audit_exports.insert_one(dict(sibling))
            sibling.pop("_id", None)
        except Exception as e:
            # Log but don't surface — the primary artefact succeeded.
            import logging
            logging.getLogger("paneltec").warning(
                "Audit pack PDF sibling generation failed for %s: %s", export_id, e)

    if sibling:
        record["pdf_sibling"] = sibling
    return record


@router.get("")
async def list_exports(user: dict = Depends(get_current_user)):
    docs = await db.audit_exports.find({"org_id": user["org_id"]}, {"_id": 0}).sort("created_at", -1).to_list(200)
    return docs


@router.get("/{eid}")
async def get_export(eid: str, user: dict = Depends(get_current_user)):
    doc = await db.audit_exports.find_one({"id": eid, "org_id": user["org_id"]}, {"_id": 0})
    if not doc:
        raise HTTPException(404, "Not found")
    return doc


@router.post("/{eid}/render-pdf", status_code=201)
async def render_pdf_sibling(eid: str, user: dict = Depends(get_current_user)):
    """Phase 3.23 — On-demand PDF sibling generation for a non-PDF pack.

    Admin-only. Idempotent: if a PDF sibling already exists for the same
    (title, date_from, date_to, scope), returns that row instead of
    creating a duplicate. Used by the Audit Exports UI when a row is
    missing its PDF counterpart (transitional state after backfill failure)."""
    if user.get("role") != "admin":
        raise HTTPException(403, "Admin only")

    row = await db.audit_exports.find_one({"id": eid, "org_id": user["org_id"]}, {"_id": 0})
    if not row:
        raise HTTPException(404, "Not found")
    if row.get("format") == "pdf":
        raise HTTPException(400, "Row is already a PDF artefact")

    # Idempotency: if a sibling already exists in this group, return it.
    existing = await db.audit_exports.find_one({
        "org_id":    user["org_id"],
        "title":     row.get("title"),
        "date_from": row.get("date_from"),
        "date_to":   row.get("date_to"),
        "scope":     row.get("scope"),
        "format":    "pdf",
    }, {"_id": 0})
    if existing:
        return existing

    # Load bundle. JSON is the canonical format; CSV-zip falls back to
    # manifest-only (same trade-off as the backfill script).
    src_path = UPLOAD_DIR / (row.get("filename") or "")
    bundle: dict = {}
    if row.get("format") == "json" and src_path.exists():
        try:
            payload = json.loads(src_path.read_bytes())
            bundle = payload.get("data") if isinstance(payload, dict) else (payload or {})
            if not isinstance(bundle, dict):
                bundle = {}
        except Exception:
            bundle = {}

    meta = {
        "export_id":    row.get("id"),
        "title":        row.get("title") or "Compliance Evidence Pack",
        "date_from":    row.get("date_from"),
        "date_to":      row.get("date_to"),
        "scope":        row.get("scope") or "Org-wide",
        "generated_at": row.get("generated_at") or row.get("created_at"),
        "generated_by": row.get("generated_by") or "—",
        "counts":       row.get("counts") or {k: len(v) for k, v in bundle.items() if isinstance(v, list)},
        "sha256":       row.get("sha256") or "",
    }
    pdf_bytes = _pdf(bundle, meta)
    pdf_sha = hashlib.sha256(pdf_bytes).hexdigest()
    pdf_id = new_id()
    pdf_filename = f"{pdf_id}.pdf"
    (UPLOAD_DIR / pdf_filename).write_bytes(pdf_bytes)
    sibling = {
        "id":           pdf_id,
        "org_id":       user["org_id"],
        "workspace_id": row.get("workspace_id"),
        "title":        meta["title"],
        "date_from":    meta["date_from"],
        "date_to":      meta["date_to"],
        "include":      row.get("include") or list(bundle.keys()),
        "format":       "pdf",
        "file_url":     f"/api/files/exports/{pdf_filename}",
        "filename":     pdf_filename,
        "sha256":       pdf_sha,
        "size_bytes":   len(pdf_bytes),
        "counts":       meta["counts"],
        "scope":        meta["scope"],
        "generated_at": meta["generated_at"],
        "generated_by": meta["generated_by"],
        "created_at":   now_iso(),
        "sibling_of":   row.get("id"),
        "rendered_on_demand": True,
    }
    await db.audit_exports.insert_one(dict(sibling))
    sibling.pop("_id", None)
    return sibling
