package com.paneltec.mobile

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.telephony.SmsMessage
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.modules.core.DeviceEventManagerModule

/**
 * BroadcastReceiver for Paneltec SMS job allocations.
 *
 * Filters by sender containing "Paneltec01" (case-insensitive) OR body containing
 * "you have been allocated to the following job".
 *
 * Emits "paneltec-sms-received" event to the RN JS layer via DeviceEventEmitter.
 * Does NOT abort broadcast — SMS still lands in the default Messages app.
 *
 * Generated by expo-sms-receiver config plugin — do NOT edit manually.
 * The senderFilter is baked in at prebuild time.
 */
class SmsReceiver : BroadcastReceiver() {
    companion object {
        private const val TAG = "PaneltecSmsReceiver"
        private const val SENDER_FILTER = "Paneltec01"
        private const val JS_EVENT = "paneltec-sms-received"

        // Set by MainApplication at startup so the receiver can emit to JS.
        @Volatile
        var reactContext: ReactApplicationContext? = null
    }

    override fun onReceive(context: Context?, intent: Intent?) {
        if (intent?.action != "android.provider.Telephony.SMS_RECEIVED") return

        val bundle: Bundle = intent.extras ?: return
        @Suppress("DEPRECATION")
        val pdus = bundle.get("pdus") as? Array<*> ?: return
        val format = bundle.getString("format") ?: "3gpp"

        val fullBody = StringBuilder()
        var senderAddress = ""

        for (pdu in pdus) {
            val msg = SmsMessage.createFromPdu(pdu as ByteArray, format)
            senderAddress = msg.displayOriginatingAddress ?: msg.originatingAddress ?: ""
            fullBody.append(msg.messageBody ?: "")
        }

        val body = fullBody.toString()
        val bodyLower = body.lowercase()

        // ── Filter ──
        val senderMatch = senderAddress.contains(SENDER_FILTER, ignoreCase = true)
        val bodyMatch = (bodyLower.contains("you have been allocated") && bodyLower.contains("job"))
                || (bodyLower.contains("truck") && bodyLower.contains("staff"))
        if (!senderMatch && !bodyMatch) {
            Log.d(TAG, "Ignoring SMS from $senderAddress — no match")
            return
        }

        Log.i(TAG, "Job SMS received from $senderAddress (${body.length} chars)")

        // ── Emit to JS ──
        try {
            val ctx = reactContext
            if (ctx != null && ctx.hasActiveReactInstance()) {
                val params = Arguments.createMap().apply {
                    putString("sender", senderAddress)
                    putString("body", body)
                    putDouble("timestamp", System.currentTimeMillis().toDouble())
                }
                ctx.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
                    .emit(JS_EVENT, params)
                Log.i(TAG, "Emitted $JS_EVENT to JS layer")
            } else {
                Log.w(TAG, "ReactContext not available — SMS queued for next app launch")
                // Persist to SharedPreferences for deferred delivery
                context?.getSharedPreferences("paneltec_sms_pending", Context.MODE_PRIVATE)
                    ?.edit()
                    ?.putString("pending_body", body)
                    ?.putString("pending_sender", senderAddress)
                    ?.putLong("pending_ts", System.currentTimeMillis())
                    ?.apply()
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to emit SMS event: ${e.message}")
        }
    }
}
