/**
 * expo-sms-receiver — Expo Config Plugin v58.13.132p1
 *
 * Injects Android SMS permissions + BroadcastReceiver into AndroidManifest.xml
 * for background SMS receipt from Paneltec01 sender.
 *
 * Usage in app.json/app.config.ts:
 *   plugins: [["./plugins/expo-sms-receiver", { senderFilter: "Paneltec01" }]]
 */
const { withAndroidManifest } = require('expo/config-plugins');
const { mkdirSync, writeFileSync, existsSync } = require('fs');
const { join } = require('path');

const RECEIVER_CLASS = 'com.paneltec.mobile.PaneltecSmsReceiver';
const RECEIVER_KT_FILENAME = 'PaneltecSmsReceiver.kt';

/**
 * Generate the Kotlin BroadcastReceiver source code.
 * Filters by sender name, extracts body, emits to JS via DeviceEventEmitter.
 */
function generateReceiverKotlin(senderFilter) {
  return `package com.paneltec.mobile

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.telephony.SmsMessage
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.modules.core.DeviceEventManagerModule

/**
 * BroadcastReceiver for Paneltec SMS job allocations.
 * Filters by sender "${senderFilter}" (case-insensitive).
 * Emits "paneltec-sms-received" event to JS layer with the raw SMS body.
 *
 * Generated by expo-sms-receiver config plugin — do NOT edit manually.
 */
class PaneltecSmsReceiver : BroadcastReceiver() {
    companion object {
        private const val TAG = "PaneltecSmsReceiver"
        private const val SENDER_FILTER = "${senderFilter}"
        private const val JS_EVENT = "paneltec-sms-received"

        // Static reference to ReactContext — set by MainApplication/ReactModule
        @Volatile
        var reactContext: ReactApplicationContext? = null
    }

    override fun onReceive(context: Context?, intent: Intent?) {
        if (intent?.action != "android.provider.Telephony.SMS_RECEIVED") return

        val bundle: Bundle = intent.extras ?: return
        val pdus = bundle.get("pdus") as? Array<*> ?: return
        val format = bundle.getString("format") ?: "3gpp"

        val fullBody = StringBuilder()
        var senderAddress = ""

        for (pdu in pdus) {
            val message = SmsMessage.createFromPdu(pdu as ByteArray, format)
            senderAddress = message.displayOriginatingAddress ?: message.originatingAddress ?: ""
            fullBody.append(message.messageBody ?: "")
        }

        // Filter by sender
        if (!senderAddress.contains(SENDER_FILTER, ignoreCase = true)) {
            Log.d(TAG, "Ignoring SMS from \$senderAddress (not \$SENDER_FILTER)")
            return
        }

        // Filter by body prefix
        val body = fullBody.toString()
        val bodyLower = body.lowercase()
        if (!bodyLower.contains("you have been allocated") && !bodyLower.contains("truck")) {
            Log.d(TAG, "Ignoring SMS — body doesn't match job pattern")
            return
        }

        Log.i(TAG, "Paneltec job SMS received from \$senderAddress (\\$\\{body.length\\} chars)")

        // Emit to JS
        try {
            val ctx = reactContext
            if (ctx != null && ctx.hasActiveReactInstance()) {
                val params = Arguments.createMap()
                params.putString("sender", senderAddress)
                params.putString("body", body)
                params.putDouble("timestamp", System.currentTimeMillis().toDouble())
                ctx.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
                    .emit(JS_EVENT, params)
                Log.i(TAG, "Emitted \$JS_EVENT to JS layer")
            } else {
                Log.w(TAG, "ReactContext not available — SMS will be picked up on next app launch")
                // TODO: persist to SharedPreferences for deferred delivery
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to emit SMS event: \${e.message}")
        }
    }
}
`;
}

function withSmsReceiver(config, props = {}) {
  const senderFilter = props.senderFilter || 'Paneltec01';

  return withAndroidManifest(config, async (modConfig) => {
    const manifest = modConfig.modResults;
    const app = manifest.manifest.application?.[0];
    if (!app) return modConfig;

    // 1. Add SMS permissions
    const perms = manifest.manifest['uses-permission'] || [];
    const addPerm = (name) => {
      if (!perms.find(p => p.$?.['android:name'] === name)) {
        perms.push({ $: { 'android:name': name } });
      }
    };
    addPerm('android.permission.RECEIVE_SMS');
    addPerm('android.permission.READ_SMS');
    manifest.manifest['uses-permission'] = perms;

    // 2. Register the BroadcastReceiver
    if (!app.receiver) app.receiver = [];
    const receiverExists = app.receiver.find(
      r => r.$?.['android:name'] === RECEIVER_CLASS
    );
    if (!receiverExists) {
      app.receiver.push({
        $: {
          'android:name': RECEIVER_CLASS,
          'android:permission': 'android.permission.BROADCAST_SMS',
          'android:exported': 'true',
        },
        'intent-filter': [{
          action: [{ $: { 'android:name': 'android.provider.Telephony.SMS_RECEIVED' } }],
        }],
      });
    }

    // 3. Write the Kotlin source file into the android project
    try {
      const androidSrcDir = join(
        modConfig.modRequest.projectRoot,
        'android', 'app', 'src', 'main', 'java', 'com', 'paneltec', 'mobile'
      );
      if (!existsSync(androidSrcDir)) {
        mkdirSync(androidSrcDir, { recursive: true });
      }
      writeFileSync(
        join(androidSrcDir, RECEIVER_KT_FILENAME),
        generateReceiverKotlin(senderFilter)
      );
    } catch (e) {
      console.warn('[expo-sms-receiver] Could not write Kotlin source:', e.message);
    }

    return modConfig;
  });
}

module.exports = withSmsReceiver;
